import type { MediaStudioConfigResponse } from '@hive/contracts';

/** Offline defaults when the Media Studio config API is unreachable. */
export const MEDIA_STUDIO_FALLBACK_CONFIG: MediaStudioConfigResponse = {
  falConfigured: false,
  kinds: [
    {
      kind: 'logo',
      label: 'Logo',
      description: 'Wordmarks and lockups with readable text.',
      defaultModel: 'ideogram/v4',
      defaultImageSize: 'square_hd',
      maxVariants: 4,
    },
    {
      kind: 'photo',
      label: 'Photo',
      description: 'Editorial and hero photography.',
      defaultModel: 'fal-ai/flux/schnell',
      defaultImageSize: 'landscape_16_9',
      maxVariants: 4,
    },
    {
      kind: 'infographic',
      label: 'Infographic',
      description: 'Charts, stats, and labeled layouts with text.',
      defaultModel: 'ideogram/v4',
      defaultImageSize: 'portrait_4_3',
      maxVariants: 4,
    },
  ],
  models: [
    {
      id: 'ideogram/v4',
      label: 'Ideogram v4',
      description: 'Readable text — best for wordmarks, lockups, and labeled infographics.',
      kinds: ['logo', 'infographic'],
      unitPrice: 0.08,
      unit: 'image',
      currency: 'USD',
    },
    {
      id: 'ideogram/v3',
      label: 'Ideogram v3',
      description: 'Earlier Ideogram — good text, lower cost than v4.',
      kinds: ['logo', 'infographic'],
      unitPrice: 0.06,
      unit: 'image',
      currency: 'USD',
    },
    {
      id: 'fal-ai/recraft-v3',
      label: 'Recraft v3',
      description: 'Flat vector brand marks and illustrative logos.',
      kinds: ['logo'],
      unitPrice: 0.04,
      unit: 'image',
      currency: 'USD',
    },
    {
      id: 'fal-ai/flux/schnell',
      label: 'Flux Schnell',
      description: 'Fast editorial photos — same default as blog hero images.',
      kinds: ['photo'],
      unitPrice: 0.003,
      unit: 'megapixel',
      currency: 'USD',
    },
    {
      id: 'fal-ai/flux/dev',
      label: 'Flux Dev',
      description: 'Higher-quality Flux photos for hero and feature imagery.',
      kinds: ['photo'],
      unitPrice: 0.025,
      unit: 'image',
      currency: 'USD',
    },
    {
      id: 'fal-ai/flux-pro/v1.1',
      label: 'Flux Pro 1.1',
      description: 'Top-tier Flux realism and detail for premium photography.',
      kinds: ['photo'],
      unitPrice: 0.05,
      unit: 'image',
      currency: 'USD',
    },
    {
      id: 'fal-ai/flux-realism',
      label: 'Flux Realism',
      description: 'Photorealistic editorial and lifestyle photography.',
      kinds: ['photo'],
      unitPrice: 0.035,
      unit: 'image',
      currency: 'USD',
    },
  ],
};
