/**
 * Hardcoded fixtures for the Intake Studio prototype (Phase 0). No backend.
 * Timestamps are relative to load time so the dashboard always shows live-ish
 * ages and expiry countdowns.
 */

import type {
  ArticleClaimsView,
  ConversationView,
  InboundMessageView,
} from './intake-view.model';

const now = Date.now();
const minutes = (n: number) => new Date(now - n * 60_000).toISOString();
const hours = (n: number) => new Date(now - n * 3_600_000).toISOString();
const days = (n: number) => new Date(now - n * 86_400_000).toISOString();
const inHours = (n: number) => new Date(now + n * 3_600_000).toISOString();
const inDays = (n: number) => new Date(now + n * 86_400_000).toISOString();

export const MOCK_CONVERSATIONS: ConversationView[] = [
  {
    id: 'conv_factcheck_1',
    contactId: 'contact_sparky',
    contactLabel: 'Mike (Sparky Electric)',
    triggerType: 'fact_check',
    blocking: true,
    resumeTarget: { type: 'claim', id: 'claim_200a', label: 'Claim: installs 200A panels' },
    status: 'in_progress',
    currentQuestionIndex: 0,
    createdAt: hours(6),
    updatedAt: minutes(40),
    questions: [
      {
        index: 0,
        text: 'We wrote that you install 200A residential panels. Is this accurate?',
        answerShape: 'yes_no',
        channel: 'sms',
        status: 'pending',
        sentAt: hours(6),
        expiresAt: inHours(18),
      },
    ],
    events: [
      { type: 'triggered', at: hours(6), detail: 'fact_check from article review' },
      { type: 'question_sent', at: hours(6), questionIndex: 0, detail: 'via SMS' },
    ],
  },
  {
    id: 'conv_review_1',
    contactId: 'contact_wri',
    contactLabel: 'Dana (Water Resources Intl)',
    triggerType: 'article_review',
    blocking: false,
    resumeTarget: { type: 'article', id: 'article_well', label: 'Draft: Hawaii well drilling permits' },
    status: 'in_progress',
    currentQuestionIndex: 0,
    createdAt: hours(20),
    updatedAt: hours(2),
    questions: [
      {
        index: 0,
        text: 'Your draft "Hawaii well drilling permits" is ready. Approve it to publish, or send notes.',
        answerShape: 'multiple_choice',
        choices: ['Approve & publish', 'Send revision notes'],
        channel: 'in_app',
        status: 'pending',
        sentAt: hours(20),
        expiresAt: inDays(3),
      },
    ],
    events: [
      { type: 'triggered', at: hours(20), detail: 'draft pipeline complete' },
      { type: 'question_sent', at: hours(20), questionIndex: 0, detail: 'via in-app' },
    ],
  },
  {
    id: 'conv_match_1',
    contactId: 'contact_sparky',
    contactLabel: 'Mike (Sparky Electric)',
    triggerType: 'project_match',
    blocking: false,
    resumeTarget: { type: 'project', id: 'pending_update_1', label: 'Update: "panel done, photos attached"' },
    status: 'pending',
    currentQuestionIndex: 0,
    createdAt: minutes(12),
    updatedAt: minutes(12),
    questions: [
      {
        index: 0,
        text: 'Which job is this update for?',
        answerShape: 'multiple_choice',
        choices: ['Henderson panel upgrade', 'Kailua remodel', 'New job'],
        channel: 'sms',
        status: 'pending',
        sentAt: minutes(12),
        expiresAt: inHours(4),
      },
    ],
    events: [
      { type: 'triggered', at: minutes(12), detail: 'ambiguous match: 2 active jobs' },
      { type: 'question_sent', at: minutes(12), questionIndex: 0, detail: 'via SMS' },
    ],
  },
  {
    id: 'conv_journalist_1',
    contactId: 'contact_artist',
    contactLabel: 'Lea (Lea Kahale Art)',
    triggerType: 'journalist',
    blocking: false,
    resumeTarget: { type: 'article', id: 'article_commission', label: 'Article need: commission process' },
    status: 'in_progress',
    currentQuestionIndex: 1,
    createdAt: days(2),
    updatedAt: hours(5),
    questions: [
      {
        index: 0,
        text: 'What inspired the Kailua coastline piece?',
        answerShape: 'free_text',
        channel: 'sms',
        status: 'answered',
        sentAt: days(2),
        expiresAt: days(1),
        answer: 'The light right after a north swell — everything goes silver.',
        answeredAt: days(2),
      },
      {
        index: 1,
        text: 'How long did that piece take from sketch to finish?',
        answerShape: 'free_text',
        channel: 'sms',
        status: 'pending',
        sentAt: hours(5),
        expiresAt: inDays(2),
      },
    ],
    events: [
      { type: 'triggered', at: days(2), detail: 'content gap: process article' },
      { type: 'question_sent', at: days(2), questionIndex: 0 },
      { type: 'answer_received', at: days(2), questionIndex: 0 },
      { type: 'question_sent', at: hours(5), questionIndex: 1 },
    ],
  },
  {
    id: 'conv_onboarding_1',
    contactId: 'contact_nurse',
    contactLabel: 'Priya (RN consultant)',
    triggerType: 'onboarding',
    blocking: false,
    resumeTarget: { type: 'site', id: 'site_priya', label: 'Onboarding: build initial content' },
    status: 'in_progress',
    currentQuestionIndex: 2,
    createdAt: days(9),
    updatedAt: days(3),
    questions: [
      {
        index: 0,
        text: 'What population do you primarily work with?',
        answerShape: 'free_text',
        channel: 'sms',
        status: 'answered',
        sentAt: days(9),
        expiresAt: days(2),
        answer: 'Critical care, mostly post-surgical cardiac.',
        answeredAt: days(8),
      },
      {
        index: 1,
        text: 'What certification are you most proud of and why?',
        answerShape: 'free_text',
        channel: 'sms',
        status: 'answered',
        sentAt: days(6),
        expiresAt: days(1),
        answer: 'CCRN — it proved I could hold the room in a code.',
        answeredAt: days(5),
      },
      {
        index: 2,
        text: 'Can you send a photo of a certificate or credential to feature?',
        answerShape: 'photo',
        channel: 'sms',
        status: 'pending',
        sentAt: days(3),
        expiresAt: inDays(4),
      },
    ],
    events: [
      { type: 'triggered', at: days(9), detail: 'new site signup' },
      { type: 'question_sent', at: days(9), questionIndex: 0 },
      { type: 'answer_received', at: days(8), questionIndex: 0 },
      { type: 'question_sent', at: days(6), questionIndex: 1 },
      { type: 'answer_received', at: days(5), questionIndex: 1 },
      { type: 'question_sent', at: days(3), questionIndex: 2 },
    ],
  },
  {
    id: 'conv_factcheck_done',
    contactId: 'contact_wri',
    contactLabel: 'Dana (Water Resources Intl)',
    triggerType: 'fact_check',
    blocking: true,
    resumeTarget: { type: 'claim', id: 'claim_depth', label: 'Claim: wells to 1,200ft' },
    status: 'complete',
    currentQuestionIndex: 0,
    createdAt: days(4),
    updatedAt: days(4),
    questions: [
      {
        index: 0,
        text: 'We wrote that you drill wells up to 1,200 feet. Correct?',
        answerShape: 'yes_no',
        channel: 'sms',
        status: 'answered',
        sentAt: days(4),
        expiresAt: days(3),
        answer: 'Closer to 1,000ft typically, 1,200 on special permits.',
        answeredAt: days(4),
      },
    ],
    events: [
      { type: 'triggered', at: days(4), detail: 'fact_check from article review' },
      { type: 'question_sent', at: days(4), questionIndex: 0 },
      { type: 'answer_received', at: days(4), questionIndex: 0 },
      { type: 'resume_executed', at: days(4), detail: 'claim corrected -> article unblocked' },
      { type: 'conversation_complete', at: days(4) },
    ],
    resumeResult: 'claim_corrected',
  },
];

export const MOCK_INBOUND_MESSAGES: InboundMessageView[] = [
  {
    id: 'msg_1',
    contactId: 'contact_sparky',
    contactLabel: 'Mike (Sparky Electric)',
    from: '+18085551234',
    body: 'panel done, photos attached',
    mediaUrls: ['https://example.com/mms/panel1.jpg', 'https://example.com/mms/panel2.jpg'],
    receivedAt: minutes(12),
    routingOutcome: 'intake_parsed',
    projectMatchResult: 'ambiguous_spawned_question',
    extractedEntities: { updateType: 'completion', entityNames: ['panel'], confidence: 0.62 },
    recordsCreated: [{ type: 'asset', id: 'asset_1', label: '2 photos staged' }],
    processingMs: 840,
  },
  {
    id: 'msg_2',
    contactId: 'contact_sparky',
    contactLabel: 'Mike (Sparky Electric)',
    from: '+18085551234',
    body: '1',
    receivedAt: minutes(8),
    routingOutcome: 'matched_conversation',
    matchedConversationId: 'conv_match_1',
    matchedQuestionIndex: 0,
    processingMs: 120,
  },
  {
    id: 'msg_3',
    contactId: 'contact_artist',
    contactLabel: 'Lea (Lea Kahale Art)',
    from: '+18085559876',
    body: 'The light right after a north swell — everything goes silver.',
    receivedAt: days(2),
    routingOutcome: 'matched_conversation',
    matchedConversationId: 'conv_journalist_1',
    matchedQuestionIndex: 0,
    processingMs: 95,
  },
  {
    id: 'msg_4',
    contactId: 'contact_unknown',
    contactLabel: 'Unknown (+18085550000)',
    from: '+18085550000',
    body: 'wrong number?',
    receivedAt: hours(3),
    routingOutcome: 'no_match',
    processingMs: 60,
  },
  {
    id: 'msg_5',
    contactId: 'contact_wri',
    contactLabel: 'Dana (Water Resources Intl)',
    from: '+18085554321',
    body: 'finished the Waianae monitoring well, 980ft',
    receivedAt: hours(30),
    routingOutcome: 'intake_parsed',
    projectMatchResult: 'auto_matched',
    extractedEntities: { updateType: 'completion', entityNames: ['Waianae monitoring well'], confidence: 0.91 },
    recordsCreated: [
      { type: 'update', id: 'update_well', label: 'Update on Waianae well' },
      { type: 'project', id: 'project_waianae', label: 'Waianae monitoring well' },
    ],
    processingMs: 910,
  },
];

export const MOCK_ARTICLE_CLAIMS: ArticleClaimsView = {
  articleId: 'article_well',
  articleTitle: 'Hawaii well drilling permits: what to expect',
  claims: [
    {
      id: 'claim_depth',
      articleId: 'article_well',
      claimText: 'We drill wells up to 1,200 feet.',
      provenance: 'ai',
      status: 'answered',
      answerValue: 'Closer to 1,000ft typically, 1,200 on special permits.',
      correctedFrom: 'We drill wells up to 1,200 feet.',
      conversationId: 'conv_factcheck_done',
    },
    {
      id: 'claim_200a',
      articleId: 'article_well',
      claimText: 'Permitting typically takes 6 to 8 weeks in Honolulu County.',
      provenance: 'ai',
      status: 'pending',
      conversationId: 'conv_factcheck_1',
    },
    {
      id: 'claim_client_1',
      articleId: 'article_well',
      claimText: 'We have operated across the Pacific Basin since 1985.',
      provenance: 'client',
      status: 'answered',
      answerValue: 'We have operated across the Pacific Basin since 1985.',
    },
    {
      id: 'claim_ai_2',
      articleId: 'article_well',
      claimText: 'All crews are OSHA-30 certified.',
      provenance: 'ai',
      status: 'pending',
    },
  ],
};
