import type { ProtopipeSiteContentPlan } from '@hive/contracts';

const NOW = '2026-06-03T12:00:00.000Z';

/** Realistic fixture for destination wedding painter — matches keyword picker persona. */
export const MOCK_STRATEGY_PLAN: ProtopipeSiteContentPlan = {
  id: 'mock-plan-1',
  siteId: 'mock-site-1',
  version: 1,
  status: 'complete',
  currentStep: 'done',
  generatedAt: NOW,
  createdAt: NOW,
  updatedAt: NOW,
  narrative: {
    headline: 'Rank for destination wedding painting in Italy',
    why: 'We lead with live-event credibility at luxury venues, then build supporting guides around Tuscany, Amalfi, and ceremony types competitors miss.',
  },
  pillars: [
    {
      clusterName: 'Tuscany venues',
      pillarKeyword: 'tuscany wedding venue',
      angle: 'Venue guides tied to live painting at villa ceremonies',
      supportingCount: 4,
    },
    {
      clusterName: 'Live wedding painting',
      pillarKeyword: 'wedding painter',
      angle: 'Process, timeline, and what couples should expect on the day',
      supportingCount: 3,
    },
    {
      clusterName: 'Destination wedding art',
      pillarKeyword: 'destination wedding painter italy',
      angle: 'Position as the specialist for international luxury weddings',
      supportingCount: 2,
    },
    {
      clusterName: 'Pricing & booking',
      pillarKeyword: 'wedding painter cost',
      angle: 'Transparent pricing and booking FAQs to capture commercial intent',
      supportingCount: 3,
    },
  ],
  calendar: [
    {
      workingTitle: 'Live Wedding Painting in Tuscany',
      suggestedKeyword: 'live wedding painting tuscany',
      intent: 'commercial',
      articleType: 'pillar',
      clusterName: 'Tuscany venues',
      clusterRole: 'pillar',
      priority: 'high',
      kind: 'new',
      proposedPublishAt: '2026-06-03',
      rationale: 'Lead pillar — anchors venue + live art intent',
    },
    {
      workingTitle: 'Tuscany Weather Tips for Outdoor Ceremonies',
      suggestedKeyword: 'tuscany outdoor wedding weather',
      intent: 'informational',
      articleType: 'howto',
      clusterName: 'Tuscany venues',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-06-03',
      rationale: 'Same-day stack — short supporting piece for pillar launch',
    },
    {
      workingTitle: 'How Live Painting Fits Your Ceremony Timeline',
      suggestedKeyword: 'wedding ceremony timeline live painting',
      intent: 'informational',
      articleType: 'howto',
      clusterName: 'Live wedding painting',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-06-01',
      rationale: 'Published earlier this week — process content',
    },
    {
      workingTitle: 'Ceremony vs Reception: Where to Place Your Artist',
      suggestedKeyword: 'wedding painter ceremony or reception',
      intent: 'informational',
      articleType: 'comparison',
      clusterName: 'Live wedding painting',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-06-04',
    },
    {
      workingTitle: 'Painting Packages for Destination Weddings',
      suggestedKeyword: 'destination wedding painting packages',
      intent: 'commercial',
      articleType: 'pillar',
      clusterName: 'Pricing & booking',
      clusterRole: 'supporting',
      priority: 'high',
      kind: 'new',
      proposedPublishAt: '2026-06-05',
    },
    {
      workingTitle: 'What to Ask Before Booking a Wedding Painter',
      suggestedKeyword: 'questions to ask wedding painter',
      intent: 'commercial',
      articleType: 'howto',
      clusterName: 'Pricing & booking',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-06-05',
      rationale: 'Stacked Friday — FAQ-style companion to packages post',
    },
    {
      workingTitle: 'Saturday Send-Off: Amalfi Coast Inspiration',
      suggestedKeyword: 'amalfi coast wedding inspiration',
      intent: 'informational',
      articleType: 'pillar',
      clusterName: 'Destination wedding art',
      clusterRole: 'supporting',
      priority: 'low',
      kind: 'new',
      proposedPublishAt: '2026-06-06',
    },
    {
      workingTitle: 'Best Destination Wedding Venues in Italy',
      suggestedKeyword: 'destination wedding venues italy',
      intent: 'commercial',
      articleType: 'howto',
      clusterName: 'Tuscany venues',
      clusterRole: 'supporting',
      priority: 'high',
      kind: 'new',
      proposedPublishAt: '2026-06-10',
    },
    {
      workingTitle: 'How to Hire a Wedding Painter Abroad',
      suggestedKeyword: 'hire wedding painter abroad',
      intent: 'commercial',
      articleType: 'pillar',
      clusterName: 'Live wedding painting',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-06-17',
    },
    {
      workingTitle: 'Villa Cetinale Wedding Guide',
      suggestedKeyword: 'villa cetinale wedding',
      intent: 'commercial',
      articleType: 'pillar',
      clusterName: 'Tuscany venues',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-06-24',
    },
    {
      workingTitle: 'Amalfi Coast Wedding Venues',
      suggestedKeyword: 'amalfi coast wedding venues',
      intent: 'commercial',
      articleType: 'howto',
      clusterName: 'Tuscany venues',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-07-01',
    },
    {
      workingTitle: 'Tuscany Villa Wedding Checklist',
      suggestedKeyword: 'tuscany villa wedding',
      intent: 'informational',
      articleType: 'pillar',
      clusterName: 'Tuscany venues',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-07-08',
    },
    {
      workingTitle: 'What Does a Wedding Painter Cost?',
      suggestedKeyword: 'wedding painter cost',
      intent: 'commercial',
      articleType: 'pillar',
      clusterName: 'Pricing & booking',
      clusterRole: 'pillar',
      priority: 'high',
      kind: 'new',
      proposedPublishAt: '2026-07-15',
    },
    {
      workingTitle: 'Live Painting vs Photography at Weddings',
      suggestedKeyword: 'live wedding painting',
      intent: 'informational',
      articleType: 'comparison',
      clusterName: 'Live wedding painting',
      clusterRole: 'pillar',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-08-05',
    },
    {
      workingTitle: 'Wedding Day Timeline for Live Artists',
      suggestedKeyword: 'wedding day timeline painter',
      intent: 'informational',
      articleType: 'pillar',
      clusterName: 'Live wedding painting',
      clusterRole: 'supporting',
      priority: 'low',
      kind: 'new',
      proposedPublishAt: '2026-08-12',
    },
    {
      workingTitle: 'Destination Wedding Painter in Italy',
      suggestedKeyword: 'destination wedding painter italy',
      intent: 'commercial',
      articleType: 'pillar',
      clusterName: 'Destination wedding art',
      clusterRole: 'pillar',
      priority: 'high',
      kind: 'new',
      proposedPublishAt: '2026-08-19',
    },
    {
      workingTitle: 'Why Couples Choose Live Wedding Art',
      suggestedKeyword: 'live wedding art',
      intent: 'informational',
      articleType: 'pillar',
      clusterName: 'Destination wedding art',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'new',
      proposedPublishAt: '2026-08-26',
    },
    {
      workingTitle: 'How to Book a Wedding Painter',
      suggestedKeyword: 'book wedding painter',
      intent: 'commercial',
      articleType: 'pillar',
      clusterName: 'Pricing & booking',
      clusterRole: 'supporting',
      priority: 'medium',
      kind: 'refresh-existing',
      existingUrl: 'https://destinationweddingpainter.com/booking',
      proposedPublishAt: '2026-09-02',
      rationale: 'Refresh thin booking page with clearer CTA and FAQ',
    },
  ],
  keywordTiers: {
    immediateFocus: [
      { phrase: 'destination wedding painter', opportunityScore: 820, tier: 'immediate_focus', source: 'plan', searchVolume: 1200, difficulty: 32 },
      { phrase: 'live wedding painting', opportunityScore: 740, tier: 'immediate_focus', source: 'plan', searchVolume: 880, difficulty: 28 },
      { phrase: 'wedding painter italy', opportunityScore: 690, tier: 'immediate_focus', source: 'plan', searchVolume: 590, difficulty: 35 },
      { phrase: 'tuscany wedding venue', opportunityScore: 650, tier: 'immediate_focus', source: 'plan', searchVolume: 2400, difficulty: 45 },
      { phrase: 'destination wedding painter italy', opportunityScore: 610, tier: 'immediate_focus', source: 'plan', searchVolume: 320, difficulty: 30 },
      { phrase: 'wedding painter cost', opportunityScore: 580, tier: 'immediate_focus', source: 'plan', searchVolume: 720, difficulty: 38 },
    ],
    longTerm: [
      { phrase: 'amalfi coast wedding venues', opportunityScore: 420, tier: 'long_term', source: 'plan', searchVolume: 1900, difficulty: 58 },
      { phrase: 'villa cetinale wedding', opportunityScore: 380, tier: 'long_term', source: 'plan', searchVolume: 210, difficulty: 42 },
      { phrase: 'live wedding art', opportunityScore: 350, tier: 'long_term', source: 'plan', searchVolume: 450, difficulty: 48 },
      { phrase: 'hire wedding painter abroad', opportunityScore: 310, tier: 'long_term', source: 'plan', searchVolume: 180, difficulty: 40 },
    ],
    longTail: [
      { phrase: 'wedding painter tuscany villa', opportunityScore: 180, tier: 'long_tail', source: 'plan', searchVolume: 90, difficulty: 22 },
      { phrase: 'live painter destination wedding', opportunityScore: 150, tier: 'long_tail', source: 'plan', searchVolume: 70, difficulty: 25 },
    ],
  },
  clusters: [
    {
      name: 'Tuscany venues',
      pillarKeyword: 'tuscany wedding venue',
      subtopic: 'Italian villa and countryside ceremonies',
      dominantIntent: 'commercial',
      members: [
        { phrase: 'tuscany wedding venue', role: 'pillar' },
        { phrase: 'destination wedding venues italy', role: 'supporting' },
        { phrase: 'villa cetinale wedding', role: 'supporting' },
        { phrase: 'amalfi coast wedding venues', role: 'supporting' },
      ],
    },
    {
      name: 'Live wedding painting',
      pillarKeyword: 'wedding painter',
      subtopic: 'On-site live art during the ceremony and reception',
      dominantIntent: 'commercial',
      members: [
        { phrase: 'wedding painter', role: 'pillar' },
        { phrase: 'live wedding painting', role: 'supporting' },
        { phrase: 'hire wedding painter abroad', role: 'supporting' },
      ],
    },
    {
      name: 'Destination wedding art',
      pillarKeyword: 'destination wedding painter italy',
      dominantIntent: 'commercial',
      members: [
        { phrase: 'destination wedding painter italy', role: 'pillar' },
        { phrase: 'live wedding art', role: 'supporting' },
      ],
    },
    {
      name: 'Pricing & booking',
      pillarKeyword: 'wedding painter cost',
      dominantIntent: 'commercial',
      members: [
        { phrase: 'wedding painter cost', role: 'pillar' },
        { phrase: 'book wedding painter', role: 'supporting' },
      ],
    },
  ],
  existingContent: {
    hostname: 'destinationweddingpainter.com',
    source: 'sitemap',
    scannedCount: 24,
    pages: [],
    refreshCandidates: [
      { url: 'https://destinationweddingpainter.com/booking', title: 'Booking', topHeadings: ['Book your painter'], wordCount: 420, schemaTypes: [], internalLinkCount: 3, isThin: true, isStale: true },
      { url: 'https://destinationweddingpainter.com/faq', title: 'FAQ', topHeadings: ['Questions'], wordCount: 380, schemaTypes: ['FAQPage'], internalLinkCount: 2, isThin: true, isStale: false },
      { url: 'https://destinationweddingpainter.com/gallery', title: 'Gallery', topHeadings: ['Recent work'], wordCount: 290, schemaTypes: [], internalLinkCount: 1, isThin: true, isStale: true },
    ],
    alreadyRanking: [
      { phrase: 'destination wedding painter', position: 4, url: 'https://destinationweddingpainter.com/' },
      { phrase: 'live wedding art', position: 7, url: 'https://destinationweddingpainter.com/our-story' },
      { phrase: 'wedding painter tuscany', position: 11, url: 'https://destinationweddingpainter.com/tuscany' },
      { phrase: 'italy wedding artist', position: 14, url: 'https://destinationweddingpainter.com/' },
      { phrase: 'destination wedding artist', position: 18, url: 'https://destinationweddingpainter.com/gallery' },
      { phrase: 'live painter wedding', position: 22, url: 'https://destinationweddingpainter.com/our-story' },
      { phrase: 'wedding painting italy', position: 28, url: 'https://destinationweddingpainter.com/tuscany' },
      { phrase: 'luxury wedding painter', position: 31, url: 'https://destinationweddingpainter.com/' },
    ],
  },
  focusStrategies: [],
};
