import type { BuildBookBlockDefinition } from './build-book.types';

const VEIL_PREVIEW_URL = 'https://cs-futureproof.pages.dev/lab/veil';
const DWP_CDN = 'https://destinationweddingpainter.com';
const VEIL_HERO_IMAGE = `${DWP_CDN}/images/hero-stash.jpg`;
const VEIL_CANVAS_IMAGE = `${DWP_CDN}/images/gallery/04.png`;

const mkVeilProps = (labUnit: string, extra: Record<string, unknown> = {}) => ({
  baselineRenderer: 'veil-site',
  baselinePreviewUrl: VEIL_PREVIEW_URL,
  labUnit,
  labBrand: 'veil',
  labCatalog: 'fold',
  ...extra,
});

export const VEIL_BASELINE_BLOCK_DEFINITIONS: BuildBookBlockDefinition[] = [
  {
    id: 'veil-baseline-hero-easel-witness',
    section: 'hero',
    label: 'Easel witness hero',
    description: 'Ceremony wide shot with easel anchored right and copy on left scrim — default live painter hero.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-hero-easel',
    astroComponent: 'sites/futureproof/src/components/veil/heroes/VeilHeroEaselWitness.astro',
    layout: 'fullbleed',
    editableFields: ['eyebrow', 'heading', 'subhead', 'backgroundImageSrc', 'primaryCtaLabel', 'primaryCtaHref', 'secondaryCtaLabel', 'secondaryCtaHref'],
    defaultProps: mkVeilProps('components/veil/heroes/VeilHeroEaselWitness.astro', {
      labCatalog: 'heroes',
      labLayout: 'veil-baseline-easel-witness',
      eyebrow: 'Live wedding paintings by Aubrey Long',
      heading: 'Your special day, captured on canvas',
      subhead:
        'Fine art painted live at your destination wedding — Maui, Hawaii, and worldwide.',
      backgroundImageSrc: VEIL_HERO_IMAGE,
      primaryCtaLabel: 'Book your date',
      primaryCtaHref: '#inquire',
      secondaryCtaLabel: 'View gallery',
      secondaryCtaHref: '#portfolio',
    }),
    seoRole: 'Sets H1, live wedding painter intent, and primary date-check CTA.',
    conversionRole: 'Introduces emotional outcome and portfolio path above the fold.',
    previewImage: VEIL_HERO_IMAGE,
  },
  {
    id: 'veil-baseline-hero-canvas-frame',
    section: 'hero',
    label: 'Canvas frame hero',
    description: 'Finished painting in gilt frame on gallery wall with copy beside the artifact.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-hero-canvas-frame',
    astroComponent: 'sites/futureproof/src/components/veil/heroes/VeilHeroCanvasFrame.astro',
    layout: 'split',
    editableFields: ['eyebrow', 'heading', 'subhead', 'paintingImageSrc', 'primaryCtaLabel', 'primaryCtaHref'],
    defaultProps: mkVeilProps('components/veil/heroes/VeilHeroCanvasFrame.astro', {
      labCatalog: 'heroes',
      labLayout: 'veil-baseline-canvas-frame',
      eyebrow: 'Live wedding painting',
      heading: 'A heirloom from the day you said yes.',
      subhead: 'Original live paintings — one canvas, your story, ready to hang.',
      paintingImageSrc: VEIL_CANVAS_IMAGE,
      primaryCtaLabel: 'Book your date',
      primaryCtaHref: '#inquire',
    }),
    seoRole: 'Artifact-led H1 for fine-art wedding painter positioning.',
    conversionRole: 'Leads with finished painting outcome before process.',
    previewImage: VEIL_CANVAS_IMAGE,
  },
  {
    id: 'veil-baseline-fold-process',
    section: 'fold',
    label: 'Live painting process',
    description: 'Four-step timeline from arrival to delivery.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-fold-process',
    astroComponent: 'sites/futureproof/src/components/veil/fold/VeilFoldProcess.astro',
    layout: 'list',
    editableFields: ['kicker', 'heading', 'steps'],
    defaultProps: mkVeilProps('components/veil/fold/VeilFoldProcess.astro', {
      kicker: 'How it works',
      heading: 'Live painting, start to finish',
      steps: [
        { step: '01', title: 'Connect', body: 'Share your date, venue, and vision. We confirm packages and travel.' },
        { step: '02', title: 'Paint live', body: 'I paint during your ceremony or reception while guests enjoy the process.' },
        { step: '03', title: 'Reveal', body: 'Most paintings reach their final form at reception\'s end — a finished work you carry home.' },
        { step: '04', title: 'Take it home', body: 'Studio refinement follows; the heirloom is ready for your wall within weeks.' },
      ],
    }),
    seoRole: 'Process language for long-tail wedding painter queries.',
    conversionRole: 'Reduces anxiety about what happens during the event.',
  },
  {
    id: 'veil-baseline-fold-portfolio',
    section: 'fold',
    label: 'Portfolio stories',
    description: 'Finished paintings with couple and venue captions.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-fold-portfolio',
    astroComponent: 'sites/futureproof/src/components/veil/fold/VeilFoldPortfolio.astro',
    layout: 'cards',
    editableFields: ['kicker', 'heading', 'items'],
    defaultProps: mkVeilProps('components/veil/fold/VeilFoldPortfolio.astro', {
      kicker: 'Portfolio',
      heading: 'Recent wedding paintings',
      items: [
        { couple: 'Maui · ceremony', venue: 'Destination wedding', note: 'Live painting during vows', image: `${DWP_CDN}/images/gallery/01.jpg` },
        { couple: 'Hawaiʻi · portrait', venue: 'Finished canvas', note: 'Bride and groom aisle moment', image: `${DWP_CDN}/images/hero.jpg` },
        { couple: 'Reception · live', venue: 'Evening celebration', note: 'Guests gather at the easel', image: `${DWP_CDN}/images/gallery/05.jpg` },
      ],
    }),
    seoRole: 'Portfolio entities for visual search and credibility.',
    conversionRole: 'Helps couples envision their own painting.',
  },
  {
    id: 'veil-baseline-fold-packages',
    section: 'fold',
    label: 'Packages + ranges',
    description: 'Ceremony, reception, and full-day with starting investment.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-fold-packages',
    astroComponent: 'sites/futureproof/src/components/veil/fold/VeilFoldPackages.astro',
    layout: 'grid',
    editableFields: ['kicker', 'heading', 'packages'],
    defaultProps: mkVeilProps('components/veil/fold/VeilFoldPackages.astro', {
      kicker: 'Packages',
      heading: 'Choose your coverage',
      packages: [
        { name: 'Ceremony', range: 'From $8,500', detail: 'Ceremony painting · 16×20 linen · finished at reception.' },
        { name: 'Signature', range: 'From $12,500', detail: 'Ceremony + reception · 24×30 linen · studio refinement included.' },
        { name: 'Estate', range: 'Custom', detail: 'Multi-panel · full weekend · international travel · white-glove install.' },
      ],
    }),
    seoRole: 'Package and pricing range language for qualified search.',
    conversionRole: 'Self-selection before inquiry.',
  },
  {
    id: 'veil-baseline-fold-reviews',
    section: 'fold',
    label: 'Couple reviews',
    description: 'Emotional testimonials from recent weddings.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-fold-reviews',
    astroComponent: 'sites/futureproof/src/components/veil/fold/VeilFoldReviews.astro',
    layout: 'reviews',
    editableFields: ['kicker', 'heading', 'reviews'],
    defaultProps: mkVeilProps('components/veil/fold/VeilFoldReviews.astro', {
      kicker: 'Couples say',
      heading: 'Reviews from recent weddings',
      reviews: [
        {
          quote:
            "Aubrey painted my husband and I perfectly — the lace on my dress, the light on our faces, the way she captured our personality. It became the piece everyone gathered around at reception.",
          author: 'Chloe & Jay',
          detail: 'Maui · 120 guests · planner-led',
        },
        {
          quote:
            "The way she captured our personality in the faces was incredible — and the small intricate details like the lace on my wedding dress.",
          author: 'Chloe & Jay',
          detail: 'Destination wedding · Maui',
        },
      ],
    }),
    seoRole: 'Review-rich content for trust signals.',
    conversionRole: 'Social proof before inquiry decision.',
  },
  {
    id: 'veil-baseline-fold-availability',
    section: 'fold',
    label: 'Availability band',
    description: 'Season scarcity and booking window.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-fold-availability',
    astroComponent: 'sites/futureproof/src/components/veil/fold/VeilFoldAvailability.astro',
    layout: 'band',
    editableFields: ['season', 'detail', 'primaryCtaLabel', 'primaryCtaHref'],
    defaultProps: mkVeilProps('components/veil/fold/VeilFoldAvailability.astro', {
      season: 'Twelve commissions · 2026 season',
      detail: 'Maui studio base · destination travel by inquiry · Peak season fills first',
      primaryCtaLabel: 'Book your date',
      primaryCtaHref: '#inquire',
    }),
    seoRole: 'Availability and seasonality context.',
    conversionRole: 'Scarcity nudge toward date inquiry.',
  },
  {
    id: 'veil-baseline-fold-faq',
    section: 'fold',
    label: 'FAQ accordion',
    description: 'Timeline, travel, canvas size, and delivery.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-fold-faq',
    astroComponent: 'sites/futureproof/src/components/veil/fold/VeilFoldFaq.astro',
    layout: 'list',
    editableFields: ['kicker', 'heading', 'items'],
    defaultProps: mkVeilProps('components/veil/fold/VeilFoldFaq.astro', {
      kicker: 'FAQ',
      heading: 'Common questions',
      items: [
        { q: 'Do you travel for destination weddings?', a: 'Yes. I am based on Maui and regularly travel throughout Hawaii, the continental US, and internationally for weddings and events.' },
        { q: 'When is the painting finished?', a: 'Most paintings are completed during the reception. You receive a finished piece to take home — timelines vary by package.' },
        { q: 'How do I check availability?', a: 'Submit the inquiry form with your date and location. We respond with packages and availability within 1–2 business days.' },
      ],
    }),
    seoRole: 'FAQ schema targets for wedding painter objections.',
    conversionRole: 'Handles logistics questions that delay contact.',
  },
  {
    id: 'veil-baseline-fold-inquire',
    section: 'close',
    label: 'Date inquiry form',
    description: 'Warm date-check form with wedding details.',
    sourceTemplateId: 'veil-live-painter-v1',
    componentId: 'baseline-veil-fold-inquire',
    astroComponent: 'sites/futureproof/src/components/veil/fold/VeilFoldInquire.astro',
    layout: 'close-form',
    editableFields: ['kicker', 'heading', 'lede', 'primaryCtaLabel', 'email'],
    defaultProps: mkVeilProps('components/veil/fold/VeilFoldInquire.astro', {
      kicker: 'Inquire',
      heading: 'Check availability for your date',
      lede: 'Share a few details — we respond within 1–2 business days with next steps.',
      primaryCtaLabel: 'Book your date',
      email: 'aubreymicahlongart@gmail.com',
    }),
    seoRole: 'Contact destination for conversion tracking.',
    conversionRole: 'Captures qualified wedding date inquiries.',
  },
];
