import type { BuildBookBlockDefinition } from './build-book.types';

const WRI_PREVIEW_URL = 'https://45108834.cs-futureproof.pages.dev/lab/wri/option-2/2b/';
const WRI_GENERATED_BASE = 'https://45108834.cs-futureproof.pages.dev/wri/generated';

export const WRI_BASELINE_BLOCK_DEFINITIONS: BuildBookBlockDefinition[] = [
  {
    id: 'wri-baseline-hero-life-proof',
    section: 'hero',
    label: 'Life + proof hero',
    description: 'WRI Option 2B full-bleed life-theme hero with exact approved copy.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-hero',
    astroComponent: 'sites/futureproof/src/components/wri/WriSite.astro',
    layout: 'fullbleed',
    editableFields: [
      'eyebrow',
      'heading',
      'subhead',
      'backgroundImageSrc',
      'backgroundImageAlt',
      'primaryCtaLabel',
      'primaryCtaHref',
      'secondaryCtaLabel',
      'secondaryCtaHref',
    ],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      optionId: 'option-2',
      option2VariantId: '2b',
      labUnit: 'components/wri/WriSite.astro',
      labBrand: 'wri',
      labLayout: 'wri-metrics',
      labCatalog: 'heroes',
      eyebrow: 'Water bringing life to Hawaii',
      heading: 'Reliable groundwater from exploration through pump install.',
      subhead:
        'WRI develops the wells that feed agriculture, municipal supply, and private estates — with licensed crews mobilized statewide from Honolulu and Kawaihae.',
      backgroundImageSrc: `${WRI_GENERATED_BASE}/hero-life-coast.jpg`,
      backgroundImageAlt:
        'Aerial documentary photograph of Hawaii sea cliffs with natural green vegetation and Pacific surf',
      primaryCtaLabel: 'Request a quote',
      primaryCtaHref: '#quote',
      secondaryCtaLabel: 'Explore services',
      secondaryCtaHref: '#services',
    },
    seoRole: 'Sets the single H1, Hawaii groundwater service intent, and life-theme brand positioning.',
    conversionRole: 'Introduces quote and service paths while anchoring the approved WRI visual tone.',
  },
  {
    id: 'wri-baseline-contract-bar',
    section: 'fold',
    label: 'Contract credibility bar',
    description: 'Approved WRI contract proof bar rendered directly below the hero.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-contract-bar',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldContractBar.astro',
    layout: 'contract-bar',
    editableFields: ['stats'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldContractBar.astro',
      labBrand: 'wri',
      labLayout: 'wri-fold-contract',
      labCatalog: 'fold',
      stats: [
        { value: '35+', label: 'Years in Hawaii' },
        { value: '$150M+', label: 'Contracts completed' },
        { value: '2,800 ft', label: 'Max well depth' },
        { value: '2', label: 'Island offices' },
      ],
    },
    seoRole: 'Adds crawlable trust proof and procurement credibility immediately after the hero.',
    conversionRole: 'Reduces buyer anxiety with contract, depth, and operating history proof.',
  },
  {
    id: 'wri-baseline-capabilities-grid',
    section: 'services',
    label: 'Capabilities grid',
    description: 'Approved WRI self-sort service cards for exploration, drilling, pump install, and monitoring.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-capabilities-grid',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldCapabilitiesGrid.astro',
    layout: 'capabilities',
    editableFields: ['heading', 'services'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldCapabilitiesGrid.astro',
      labBrand: 'wri',
      labLayout: 'wri-fold-capabilities',
      labCatalog: 'fold',
      heading: 'Groundwater capabilities from exploration through pump install.',
      services: ['Exploration', 'Deep drilling', 'Pump install', 'Monitoring'],
    },
    seoRole: 'Exposes core service entities for groundwater drilling and pump search intent.',
    conversionRole: 'Lets visitors self-select the service lane that matches their project.',
  },
  {
    id: 'wri-baseline-life-proof-split',
    section: 'proof',
    label: 'Life + proof split',
    description: 'Approved Option 2B SEO split intro block.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-seo-band',
    astroComponent: 'sites/futureproof/src/components/wri/WriSeoBand.astro',
    layout: 'split',
    editableFields: ['kicker', 'heading', 'lede', 'bullets'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/WriSeoBand.astro',
      seoCopyBlockId: 'life-narrative-c',
      kicker: 'Life · reliability · depth',
      heading: 'Water resources engineering rooted in Hawaii place.',
      lede:
        'We drill where water matters most — coastal recharge zones, central valley agriculture, and upland estates that cannot depend on surface supply alone. Licensed crews, documented testing, and pump install close the loop.',
      bullets: [
        'Watershed-aware exploration methods',
        'Deep basalt drilling to 2,800 ft',
        'Pump install and yield verification',
        'Honolulu and Kawaihae mobilization',
      ],
    },
    seoRole: 'Adds keyword-rich process and place language without duplicating the hero H1.',
    conversionRole: 'Connects emotional life-theme messaging to concrete technical proof.',
  },
  {
    id: 'wri-baseline-project-lifecycle',
    section: 'areas',
    label: 'Project lifecycle',
    description: 'Approved WRI permit-to-production process section.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-project-lifecycle',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldProjectLifecycle.astro',
    layout: 'list',
    editableFields: ['steps'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldProjectLifecycle.astro',
      steps: ['Assess', 'Permit', 'Mobilize', 'Drill', 'Commission'],
    },
    seoRole: 'Captures project process language for procurement and owner education.',
    conversionRole: 'Shows a clear path from first conversation to commissioned well.',
  },
  {
    id: 'wri-baseline-featured-well',
    section: 'proof',
    label: 'Featured well',
    description: 'Approved WRI featured well proof section.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-featured-well',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldFeaturedWell.astro',
    layout: 'featured',
    editableFields: ['heading', 'metrics', 'imageSrc', 'imageAlt'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldFeaturedWell.astro',
      heading: 'Featured deep well capability',
      metrics: ['2,800 ft depth capability', 'Production testing', 'Pump commissioning'],
      imageSrc: `${WRI_GENERATED_BASE}/hero-life-valley.jpg`,
      imageAlt: 'Green Hawaii valley with a winding river and morning mist',
    },
    seoRole: 'Supplies E-E-A-T proof around well depth, yield, and field execution.',
    conversionRole: 'Turns abstract capability into a concrete project proof point.',
  },
  {
    id: 'wri-baseline-sidebar-facts',
    section: 'proof',
    label: 'Sidebar facts',
    description: 'Approved WRI mid-page narrative with sticky facts column.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-seo-band',
    astroComponent: 'sites/futureproof/src/components/wri/WriSeoBand.astro',
    layout: 'stats',
    editableFields: ['heading', 'lede', 'facts'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/WriSeoBand.astro',
      seoCopyBlockId: 'prose-sidebar',
      heading: 'Why Hawaii contractors choose WRI',
      lede:
        'Groundwater development is a long-term asset. WRI combines exploration discipline, deep drilling capability, and pump expertise so your well performs from commissioning through decades of production.',
      facts: [
        { label: 'Max depth', value: '2,800 ft' },
        { label: 'Contracts', value: '$150M+' },
        { label: 'Experience', value: 'Since 1989' },
        { label: 'Offices', value: 'Oahu · Big Island' },
      ],
    },
    seoRole: 'Reinforces expertise, experience, authority, and trust signals mid-page.',
    conversionRole: 'Keeps proof visible at the decision point before the close.',
  },
  {
    id: 'wri-baseline-regulatory-trust',
    section: 'proof',
    label: 'Regulatory trust',
    description: 'Approved WRI compliance and credential trust section.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-regulatory-trust',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldRegulatoryTrust.astro',
    layout: 'cards',
    editableFields: ['credentials'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldRegulatoryTrust.astro',
      credentials: ['Licensed drillers', 'Permit coordination', 'Testing documentation'],
    },
    seoRole: 'Supports authority for regulated well drilling and pump installation queries.',
    conversionRole: 'Assures agency and private buyers that compliance is handled.',
  },
  {
    id: 'wri-baseline-island-coverage',
    section: 'areas',
    label: 'Island coverage',
    description: 'Approved WRI Hawaii island service coverage section.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-island-coverage',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldIslandCoverage.astro',
    layout: 'map',
    editableFields: ['areas'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldIslandCoverage.astro',
      areas: ['Oahu', 'Hawaii Island', 'Maui', 'Kauai', 'Molokai', 'Lanai'],
    },
    seoRole: 'Adds local coverage language for Hawaii island and Pacific Basin searches.',
    conversionRole: 'Confirms mobilization reach for local and neighbor-island buyers.',
  },
  {
    id: 'wri-baseline-rig-gallery-cta',
    section: 'close',
    label: 'Rig gallery + quote CTA',
    description: 'Approved WRI field gallery and final quote CTA.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-rig-gallery-cta',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldRigGalleryCta.astro',
    layout: 'close-form',
    editableFields: ['heading', 'body', 'ctaLabel', 'ctaHref', 'images'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldRigGalleryCta.astro',
      heading: 'Talk with WRI about your well project.',
      body: 'Share your location, intended use, and schedule. We will help scope exploration, drilling, pump install, and permitting next steps.',
      ctaLabel: 'Request a quote',
      ctaHref: '#quote',
      images: [
        `${WRI_GENERATED_BASE}/hero-life-watershed.jpg`,
        `${WRI_GENERATED_BASE}/hero-life-fields.jpg`,
        `${WRI_GENERATED_BASE}/hero-life-coast.jpg`,
      ],
    },
    seoRole: 'Closes with service, location, and contact language tied to the page topic.',
    conversionRole: 'Moves qualified visitors into a quote conversation.',
  },
];
