import type { BuildBookBlockDefinition } from './build-book.types';
import {
  HIL_ASSETS,
  HIL_DEFAULT_FAQ,
  HIL_DEFAULT_GALLERY,
  HIL_DEFAULT_SERVICES,
  HIL_SITE_ORIGIN,
} from './baseline/hil/build-book-hil-content.constants';

const HIL_PREVIEW_URL = `${HIL_SITE_ORIGIN}/lab/hil/blackstone`;

export const HIL_BASELINE_BLOCK_DEFINITIONS: BuildBookBlockDefinition[] = [
  {
    id: 'hil-baseline-hero-canopy',
    section: 'hero',
    label: 'Canopy hero',
    description: 'Blackstone landscaping hero with primary estimate CTA.',
    sourceTemplateId: 'blackstone-landscaping-v1',
    componentId: 'baseline-hil-hero',
    astroComponent: 'sites/futureproof/src/components/hil/heroes/HilHeroCanopy.astro',
    layout: 'fullbleed',
    editableFields: ['eyebrow', 'heading', 'subhead', 'backgroundImageSrc', 'primaryCtaLabel', 'primaryCtaHref'],
    defaultProps: {
      baselineRenderer: 'hil-site',
      baselinePreviewUrl: HIL_PREVIEW_URL,
      labLayout: 'hil-baseline-hero-canopy',
      labCatalog: 'heroes',
      eyebrow: 'Anchorage, Alaska',
      heading: 'Family-owned custom landscaping and outdoor living spaces.',
      subhead: 'Premiere Alaskan landscaping — free estimates at (907) 306-6415.',
      backgroundImageSrc: HIL_ASSETS.heroCanopy,
      primaryCtaLabel: 'Get my free estimate',
      primaryCtaHref: '#quote',
    },
    seoRole: 'Landscaping service intent and local trust above the fold.',
    conversionRole: 'Routes visitors to quote request or phone.',
  },
  {
    id: 'hil-baseline-service-grid',
    section: 'services',
    label: 'Service grid',
    description: 'Landscaping service cards with estimate links.',
    sourceTemplateId: 'blackstone-landscaping-v1',
    componentId: 'services-grid',
    layout: 'grid',
    editableFields: ['heading', 'subhead', 'services'],
    defaultProps: {
      baselineRenderer: 'hil-site',
      kicker: 'Services',
      heading: 'Custom landscaping services',
      subhead: 'Outdoor living, sod, grading, and seasonal cleanup — free estimates.',
      services: structuredClone(HIL_DEFAULT_SERVICES),
    },
    seoRole: 'Service entity coverage for local SEO.',
    conversionRole: 'Self-select service path to quote tool.',
  },
  {
    id: 'hil-baseline-work-gallery',
    section: 'proof',
    label: 'Work gallery',
    description: 'Verified Facebook project gallery.',
    sourceTemplateId: 'blackstone-landscaping-v1',
    componentId: 'gallery-showcase',
    layout: 'grid',
    editableFields: ['heading', 'subhead', 'moreLabel', 'moreHref', 'images'],
    defaultProps: {
      baselineRenderer: 'hil-site',
      kicker: 'Photos',
      heading: 'Verified gallery',
      subhead: 'Recent Blackstone Landscaping AK projects from Facebook.',
      moreLabel: 'See more on Facebook',
      moreHref: 'https://www.facebook.com/p/Blackstone-Landscaping-Ak-LLC-61578191737297/',
      images: structuredClone(HIL_DEFAULT_GALLERY),
    },
    seoRole: 'Portfolio proof for landscaping queries.',
    conversionRole: 'Build trust before quote or schedule actions.',
  },
  {
    id: 'hil-baseline-before-after',
    section: 'proof',
    label: 'Before & after',
    description: 'Side-by-side transformation proof band.',
    sourceTemplateId: 'blackstone-landscaping-v1',
    componentId: 'before-after',
    astroComponent: '@client-sites/theme/components/landing/BeforeAfter.astro',
    layout: 'split',
    editableFields: ['kicker', 'title', 'lede', 'before', 'after'],
    defaultProps: {
      baselineRenderer: 'hil-site',
      kicker: 'Results',
      title: 'Before & after',
      lede: 'Same Anchorage property — rock wall and grading from the public Facebook page (July 2025).',
      before: {
        image: HIL_ASSETS.galleryBobcat,
        alt: 'Bobcat grading at a rock wall install in progress',
        label: 'Before',
        headline: 'Site prep & grading',
        detail: 'Equipment tracks, layout, and wall base in progress',
      },
      after: {
        image: HIL_ASSETS.galleryWall,
        alt: 'Finished natural stone retaining wall with gravel bed',
        label: 'After',
        headline: 'Rock retaining wall',
        detail: 'Natural stone wall with gravel drain line along the home',
      },
    },
    seoRole: 'Outcome proof for conversion-oriented searches.',
    conversionRole: 'Visual proof before quote request.',
  },
  {
    id: 'hil-baseline-scheduler-embed',
    section: 'close',
    label: 'Schedule / Calendly',
    description: 'Calendly scheduler embed for consultation booking.',
    sourceTemplateId: 'blackstone-landscaping-v1',
    componentId: 'scheduler-embed',
    astroComponent: '@client-sites/theme/components/landing/SchedulerEmbed.astro',
    layout: 'close-form',
    editableFields: ['kicker', 'title', 'lede', 'url', 'embedHeight', 'connected', 'demoStatus'],
    defaultProps: {
      baselineRenderer: 'hil-site',
      kicker: 'Schedule',
      title: 'Book a 15-minute call',
      lede: 'Pick an open slot — we’ll confirm your project scope and next steps on the call.',
      url: 'https://calendly.com/server-futureproofsystems/30min',
      embedHeight: 580,
      connected: false,
      demoStatus: 'Preview only — booking connects when you go live.',
    },
    seoRole: 'Schedule-meeting intent capture.',
    conversionRole: 'Book consultation without phone tag.',
    renderMode: 'interactive-stub',
  },
  {
    id: 'hil-baseline-quote-form',
    section: 'close',
    label: 'Quote tool',
    description: 'Preact quote request wizard stub.',
    sourceTemplateId: 'blackstone-landscaping-v1',
    componentId: 'quote-request-form',
    layout: 'close-form',
    editableFields: ['kicker', 'title', 'lede', 'heading', 'subhead', 'submitLabel'],
    defaultProps: {
      baselineRenderer: 'hil-site',
      kicker: 'Quote',
      title: 'Send project details',
      lede: 'Select services, add your address, and upload photos — we respond with availability and next steps.',
      heading: 'Send project details',
      submitLabel: 'Submit quote request',
      layout: 'wizard',
      siteSlug: 'blackstone-landscaping',
      apiBaseUrl: 'https://api.example.com',
    },
    seoRole: 'Lead capture for quote-intent visitors.',
    conversionRole: 'Capture project details with photos.',
    renderMode: 'interactive-stub',
  },
  {
    id: 'hil-baseline-faq',
    section: 'areas',
    label: 'FAQ',
    description: 'Common landscaping questions accordion.',
    sourceTemplateId: 'blackstone-landscaping-v1',
    componentId: 'faq-accordion',
    layout: 'tabs',
    editableFields: ['heading', 'subhead', 'items'],
    defaultProps: {
      baselineRenderer: 'hil-site',
      kicker: 'FAQ',
      heading: 'Questions from Anchorage homeowners',
      subhead: 'Straight answers about services and typical area pricing.',
      items: structuredClone(HIL_DEFAULT_FAQ),
    },
    seoRole: 'FAQ rich results and objection handling.',
    conversionRole: 'Answer logistics before contact.',
  },
  {
    id: 'hil-baseline-cta-banner',
    section: 'close',
    label: 'CTA banner',
    description: 'Final estimate call-to-action band.',
    sourceTemplateId: 'blackstone-landscaping-v1',
    componentId: 'cta-banner',
    layout: 'band',
    editableFields: ['heading', 'body', 'subhead', 'ctaLabel', 'ctaHref'],
    defaultProps: {
      baselineRenderer: 'hil-site',
      heading: 'Ready for a free estimate?',
      subhead: 'Call (907) 306-6415 or send project photos through the quote form.',
      body: 'Call (907) 306-6415 or send project photos through the quote form.',
      ctaLabel: 'Get my free estimate',
      ctaHref: '#quote',
    },
    seoRole: 'Final conversion anchor on homepage.',
    conversionRole: 'Drive quote or phone action.',
  },
];
