import type { BuildBookBlockDefinition } from './build-book.types';

const SPARKY_PREVIEW_URL = 'https://cs-futureproof.pages.dev/lab/sparky';
const SPARKY_ASSETS = 'https://cs-futureproof.pages.dev/sparky/site';

const mkSparkyProps = (labUnit: string, extra: Record<string, unknown> = {}) => ({
  baselineRenderer: 'sparky-site',
  baselinePreviewUrl: SPARKY_PREVIEW_URL,
  labUnit,
  labBrand: 'sparky',
  labCatalog: 'fold',
  ...extra,
});

export const SPARKY_BASELINE_BLOCK_DEFINITIONS: BuildBookBlockDefinition[] = [
  {
    id: 'sparky-baseline-hero-callout',
    section: 'hero',
    label: 'Proof callout hero',
    description: 'Sparky full-bleed callout hero with centered copy and logo mark.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-hero',
    astroComponent: 'sites/futureproof/src/components/sparky/heroes/SparkyHeroCallout.astro',
    layout: 'fullbleed',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 14 },
    editableFields: ['eyebrow', 'heading', 'subhead', 'backgroundImageSrc', 'primaryCtaLabel', 'primaryCtaHref', 'secondaryCtaLabel', 'secondaryCtaHref'],
    defaultProps: mkSparkyProps('components/sparky/heroes/SparkyHeroCallout.astro', {
      labCatalog: 'heroes',
      labLayout: 'sparky-baseline-callout',
      eyebrow: 'Makawao · Maui, Hawaii',
      heading: 'Quality electrical services for Maui homes and businesses.',
      subhead: 'Local family-owned electricians — residential, commercial, solar off-grid & grid-tied, repairs, and new builds. Serving the community since 2015.',
      backgroundImageSrc: `${SPARKY_ASSETS}/hero-aerial.jpg`,
      primaryCtaLabel: 'Call now',
      primaryCtaHref: 'tel:8082684107',
      secondaryCtaLabel: 'View services',
      secondaryCtaHref: '#services',
    }),
    seoRole: 'Sets H1, Maui electrical service intent, and primary call path.',
    conversionRole: 'Introduces call and services paths with local proof tone.',
  },
  {
    id: 'sparky-baseline-trust-stats',
    section: 'fold',
    label: 'Trust + stats strip',
    description: 'Credential bar and stat band immediately below the hero.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-trust-stats',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldTrustStats.astro',
    layout: 'metrics',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 4 },
    editableFields: ['trust', 'stats'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldTrustStats.astro', {
      labLayout: 'sparky-baseline-trust-stats',
      trust: [
        { label: 'Family owned', detail: 'Local Maui business' },
        { label: 'Residential & commercial', detail: 'Repairs to new builds' },
        { label: 'Solar specialists', detail: 'Off-grid & grid-tied' },
        { label: 'Partner brands', detail: 'GE · Sol-Ark · Enphase · REC · Eaton · Tesla' },
      ],
      stats: [
        { value: '10+', label: 'Years experience' },
        { value: '2015', label: 'Founded on Maui' },
        { value: '100%', label: 'Work guaranteed' },
      ],
    }),
    seoRole: 'Adds crawlable trust proof near the top of the page.',
    conversionRole: 'Reduces anxiety with license, longevity, and guarantee proof.',
  },
  {
    id: 'sparky-baseline-services-grid',
    section: 'services',
    label: 'Services grid',
    description: 'Four photo service cards for self-sort routing.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-services-grid',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldServicesGrid.astro',
    layout: 'capabilities',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['kicker', 'heading', 'lede', 'services'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldServicesGrid.astro', {
      kicker: 'Services',
      heading: 'Residential, commercial, and solar',
      lede: 'With more than 10 years of experience, a reputation for quality, and versatile specialists for new construction and renovation projects.',
      services: [
        { title: 'Residential service', body: 'Emergency service, wiring, EV chargers, pool & spa, lighting, outlets, and repairs. No job too small.', image: `${SPARKY_ASSETS}/service-residential.jpg`, href: '#services' },
        { title: 'Commercial & new builds', body: 'Restaurant wiring, service upgrades 100–200A, apartment wiring, A/C, and computer wiring.', image: `${SPARKY_ASSETS}/service-commercial.jpg`, href: '#services' },
        { title: 'Solar', body: 'Residential and commercial solar, battery storage, off-grid systems, and monitoring.', image: `${SPARKY_ASSETS}/service-solar.jpg`, href: '#services' },
        { title: 'Remodels & repairs', body: 'Renovation electrical, security lighting, ceiling fans, and guaranteed repair work.', image: `${SPARKY_ASSETS}/project-residential.jpg`, href: 'tel:8082684107' },
      ],
    }),
    seoRole: 'Exposes core service entities for local electrical search.',
    conversionRole: 'Lets visitors self-select residential, commercial, or solar paths.',
  },
  {
    id: 'sparky-baseline-brand-partners',
    section: 'proof',
    label: 'Brand partners',
    description: 'Manufacturer and partner logo strip.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-brand-partners',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldBrandPartners.astro',
    layout: 'band',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 3.5 },
    editableFields: ['title', 'brands'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldBrandPartners.astro', {
      title: 'We work with the best brands in the Market.',
      brands: [
        { name: 'General Electric', src: `${SPARKY_ASSETS}/brand-ge.png` },
        { name: 'Sol-Ark', src: `${SPARKY_ASSETS}/brand-sol-ark.png` },
        { name: 'Enphase', src: `${SPARKY_ASSETS}/brand-enphase.png` },
        { name: 'REC Certified Solar Pro', src: `${SPARKY_ASSETS}/brand-rec-solar.png` },
        { name: 'Eaton', src: `${SPARKY_ASSETS}/brand-eaton.png` },
        { name: 'Tesla', src: `${SPARKY_ASSETS}/brand-tesla.png` },
      ],
    }),
    seoRole: 'Supports authority with named manufacturer partnerships.',
    conversionRole: 'Signals quality equipment choices to solar and panel buyers.',
  },
  {
    id: 'sparky-baseline-process',
    section: 'fold',
    label: 'Process timeline',
    description: 'Numbered contact-to-completion process steps.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-process',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldProcess.astro',
    layout: 'list',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['kicker', 'title', 'steps'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldProcess.astro', {
      kicker: 'How it works',
      title: 'From contact to completed project',
      steps: [
        { step: '01', title: 'Contact us', body: 'Call, email, or send a brief description of your residential, commercial, or solar project.' },
        { step: '02', title: 'Scope & quote', body: 'Versatile specialists support new construction and renovation projects at every level.' },
        { step: '03', title: 'Install', body: 'Residential wiring, commercial upgrades, EV chargers, or off-grid and grid-tied solar systems.' },
        { step: '04', title: 'Guaranteed work', body: 'All work guaranteed — from small repairs to large commercial installations.' },
      ],
    }),
    seoRole: 'Captures process language for homeowner education queries.',
    conversionRole: 'Shows what happens after the first call.',
  },
  {
    id: 'sparky-baseline-reviews',
    section: 'proof',
    label: 'Reviews strip',
    description: 'Named review excerpts and about-us proof.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-reviews',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldReviews.astro',
    layout: 'reviews',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['kicker', 'heading', 'source', 'reviews'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldReviews.astro', {
      kicker: 'About Sparky',
      heading: 'Quality, transparency, and guaranteed work',
      source: 'From sparkyelectrichawaii.com',
      reviews: [
        { name: 'Sparky Electric LLC', area: 'About us', text: 'A local family owned business providing quality and friendly electrical services to the community.' },
        { name: 'Jake Noble', area: 'Owner · since 2015', text: 'Focused on clean and efficient work after a decade in the trade before starting the company.' },
        { name: 'Our promise', area: 'Services', text: 'No job too small — residential repairs, commercial installs, and off-grid solar. All work guaranteed.' },
      ],
    }),
    seoRole: 'Adds social proof language for trust queries.',
    conversionRole: 'Builds confidence before the final CTA.',
  },
  {
    id: 'sparky-baseline-why-evidence',
    section: 'proof',
    label: 'Why us · evidence',
    description: 'Claim + proof pairs instead of generic adjectives.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-why-evidence',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldWhyEvidence.astro',
    layout: 'cards',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 6 },
    editableFields: ['kicker', 'heading', 'credentials'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldWhyEvidence.astro', {
      kicker: 'Why Sparky',
      heading: 'Evidence, not adjectives',
      credentials: [
        { claim: 'Family owned on Maui', proof: 'Sparky Electric LLC works alongside the community with transparency between customer and tradesmen.' },
        { claim: 'Versatile specialists', proof: 'Residential service, commercial wiring, repairs, remodels, and solar — including off-grid systems.' },
        { claim: 'Best brands in the market', proof: 'We partner with GE, Sol-Ark, Enphase, REC Certified Solar Pro, Eaton, Tesla, and other trusted manufacturers.' },
      ],
    }),
    seoRole: 'Differentiation copy for Maui electrical searches.',
    conversionRole: 'Connects brand claims to concrete proof.',
  },
  {
    id: 'sparky-baseline-project-feature',
    section: 'proof',
    label: 'Featured project',
    description: 'Split project proof with metrics.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-project-feature',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldProjectFeature.astro',
    layout: 'featured',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['kicker', 'heading', 'caption', 'metrics', 'imageSrc', 'imageAlt'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldProjectFeature.astro', {
      kicker: 'Featured project',
      heading: 'From small repairs to large commercial installs',
      caption: 'Maui · residential & commercial · 2025',
      imageSrc: `${SPARKY_ASSETS}/project-commercial.jpg`,
      imageAlt: 'Commercial electrical installation on Maui',
      metrics: [
        { label: 'Scope', value: 'Residential repairs to commercial solar' },
        { label: 'Specialty', value: 'Off-grid systems & monitoring' },
        { label: 'Coverage', value: 'Maui — Makawao & island-wide' },
      ],
    }),
    seoRole: 'Project proof for E-E-A-T signals.',
    conversionRole: 'Turns capability into a concrete job story.',
  },
  {
    id: 'sparky-baseline-areas-map',
    section: 'areas',
    label: 'Service areas',
    description: 'Maui coverage map band and city chips.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-areas-map',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldAreasMap.astro',
    layout: 'map',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['kicker', 'heading', 'lede', 'mapCaption', 'areas', 'mapImageSrc'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldAreasMap.astro', {
      kicker: 'Service areas',
      heading: 'Maui coverage — Makawao and island-wide',
      lede: 'Based in Makawao and serving homeowners and businesses across Maui.',
      mapCaption: 'Makawao · Central Maui · South Shore · West Maui',
      mapImageSrc: `${SPARKY_ASSETS}/hero-aerial.jpg`,
      areas: ['Makawao', 'Kahului', 'Wailuku', 'Kihei', 'Lahaina', 'Upcountry'],
    }),
    seoRole: 'Local coverage language for geo search.',
    conversionRole: 'Confirms service reach for Maui visitors.',
  },
  {
    id: 'sparky-baseline-gallery-cta',
    section: 'close',
    label: 'Gallery + quote CTA',
    description: 'Before/after gallery into phone close.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-gallery-cta',
    astroComponent: 'sites/futureproof/src/components/sparky/fold/SparkyFoldGalleryCta.astro',
    layout: 'close-form',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 11 },
    editableFields: ['kicker', 'heading', 'phone', 'email', 'phoneHref', 'gallery'],
    defaultProps: mkSparkyProps('components/sparky/fold/SparkyFoldGalleryCta.astro', {
      kicker: 'Recent work',
      heading: 'Before & after on Maui jobs',
      phone: '(808) 268-4107',
      email: 'sparkyjakellc@gmail.com',
      phoneHref: 'tel:8082684107',
      gallery: [
        { label: 'Residential wiring', image: `${SPARKY_ASSETS}/project-residential.jpg`, location: 'Maui' },
        { label: 'Panel & service work', image: `${SPARKY_ASSETS}/project-panel.jpg`, location: 'Maui' },
        { label: 'Solar installation', image: `${SPARKY_ASSETS}/service-solar.jpg`, location: 'Maui' },
        { label: 'Commercial project', image: `${SPARKY_ASSETS}/project-commercial.jpg`, location: 'Maui' },
      ],
    }),
    seoRole: 'Closes page with project proof and contact intent.',
    conversionRole: 'Drives phone and email inquiries.',
  },
  {
    id: 'sparky-baseline-field-notes',
    section: 'close',
    label: 'Field notes',
    description: 'SEO article cards and serving line.',
    sourceTemplateId: 'sparky-electric-trades-v1',
    componentId: 'baseline-sparky-field-notes',
    astroComponent: 'sites/futureproof/src/components/sparky/SparkyFieldNotes.astro',
    layout: 'grid',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 7 },
    editableFields: ['kicker', 'heading', 'lede', 'articles', 'areas'],
    defaultProps: mkSparkyProps('components/sparky/SparkyFieldNotes.astro', {
      kicker: 'Field Notes',
      heading: 'Guides for Maui homeowners',
      lede: 'SEO-ready topics aligned with Sparky Electric services — solar, repairs, and upgrades.',
      articles: [
        { category: 'Guides', title: 'Residential solar on Maui: off-grid vs grid-tied', image: `${SPARKY_ASSETS}/service-solar.jpg` },
        { category: 'Safety', title: 'Hurricane season prep for island electrical panels', image: `${SPARKY_ASSETS}/hero-aerial.jpg` },
        { category: 'Solar', title: 'EV charger installs for Maui homes', image: `${SPARKY_ASSETS}/service-residential.jpg` },
      ],
      areas: ['Makawao', 'Kahului', 'Wailuku', 'Kihei', 'Lahaina', 'Upcountry'],
    }),
    seoRole: 'Content hub entry for long-tail electrical topics.',
    conversionRole: 'Keeps SEO visitors in the Sparky ecosystem.',
  },
];
