import type { BuildBookBlockDefinition } from './build-book.types';

/** All baseline templates — universal variants appear in compatible + all pattern filters. */
export const BUILD_BOOK_ALL_TEMPLATE_IDS = [
  'sparky-electric-trades-v1',
  'wri-field-authority-v1',
  'wilco-consulting-v1',
  'veil-live-painter-v1',
  'blackstone-landscaping-v1',
] as const;

const NEUTRAL_STATS = [
  { value: '15+', label: 'Years in business' },
  { value: '500+', label: 'Projects completed' },
  { value: '4.9', label: 'Average rating' },
  { value: '100%', label: 'Licensed & insured' },
];

const NEUTRAL_FAQ = [
  {
    q: 'What areas do you serve?',
    a: 'We work across our local metro and surrounding communities. Share your address when you request a quote and we will confirm coverage.',
  },
  {
    q: 'How do I get a quote?',
    a: 'Call, email, or use the contact form on this page. Most quotes start with a short scope conversation and optional site visit.',
  },
  {
    q: 'Are you licensed and insured?',
    a: 'Yes. We carry the licenses and insurance required for the work we perform and can provide documentation on request.',
  },
  {
    q: 'How long does a typical project take?',
    a: 'Timelines depend on scope, permits, and weather. We give a clear schedule before work begins and keep you updated throughout.',
  },
];

const NEUTRAL_PROCESS_STEPS = [
  {
    step: '01',
    title: 'Tell us what you need',
    body: 'Share your project scope, location, and timeline — phone, form, or email works.',
  },
  {
    step: '02',
    title: 'Scope & quote',
    body: 'We confirm fit, walk the site or plans when needed, and send a clear proposal.',
  },
  {
    step: '03',
    title: 'Schedule & execute',
    body: 'Crew mobilizes on the agreed date with updates through install or field work.',
  },
  {
    step: '04',
    title: 'Walkthrough & wrap-up',
    body: 'Final review, documentation, and support so you know what was delivered.',
  },
] as const;

const VISUAL_PROCESS_STEPS = NEUTRAL_PROCESS_STEPS.map((step) => ({
  ...step,
  image: '',
  imageAlt: step.title,
}));

const NEUTRAL_TESTIMONIALS = [
  {
    quote:
      'They showed up on time, explained every step, and the finished work looks better than we expected. Would hire again without hesitation.',
    name: 'Sarah M.',
    role: 'Homeowner',
  },
  {
    quote:
      'Clear quote, no surprise charges, and the crew kept the site tidy through the whole project. Communication was excellent.',
    name: 'James T.',
    role: 'Property manager',
  },
  {
    quote:
      'Professional from first call to final walkthrough. They handled permits and scheduling so we did not have to chase details.',
    name: 'Elena R.',
    role: 'Small business owner',
  },
];

const NEUTRAL_SERVICES = [
  {
    title: 'Core service',
    body: 'Describe your primary offer — scope, who it is for, and what a typical engagement includes.',
    image: '',
    imageAlt: 'Core service',
    href: '#inquiry',
  },
  {
    title: 'Specialty work',
    body: 'Highlight a secondary lane — repairs, upgrades, seasonal work, or niche expertise.',
    image: '',
    imageAlt: 'Specialty work',
    href: '#inquiry',
  },
  {
    title: 'Commercial & larger jobs',
    body: 'Signal capacity for bigger scopes — multi-day projects, crews, documentation, and scheduling.',
    image: '',
    imageAlt: 'Commercial projects',
    href: '#inquiry',
  },
  {
    title: 'Maintenance & support',
    body: 'Ongoing programs, warranties, or follow-up visits that keep clients coming back.',
    image: '',
    imageAlt: 'Maintenance support',
    href: '#inquiry',
  },
];

const NEUTRAL_GALLERY = [
  { image: '', caption: 'Recent project', imageAlt: 'Recent project' },
  { image: '', caption: 'Detail shot', imageAlt: 'Detail shot' },
  { image: '', caption: 'Finished result', imageAlt: 'Finished result' },
  { image: '', caption: 'On-site work', imageAlt: 'On-site work' },
  { image: '', caption: 'Crew in action', imageAlt: 'Crew in action' },
  { image: '', caption: 'Client-ready deliverable', imageAlt: 'Client-ready deliverable' },
];

const NEUTRAL_LOGOS = [
  { name: 'Partner one', image: '', alt: 'Partner one' },
  { name: 'Partner two', image: '', alt: 'Partner two' },
  { name: 'Partner three', image: '', alt: 'Partner three' },
  { name: 'Partner four', image: '', alt: 'Partner four' },
  { name: 'Partner five', image: '', alt: 'Partner five' },
  { name: 'Partner six', image: '', alt: 'Partner six' },
];

const NEUTRAL_CASE_METRICS = [
  { value: '6 weeks', label: 'Project timeline' },
  { value: '12%', label: 'Under budget' },
  { value: '100%', label: 'Inspection pass rate' },
];

const NEUTRAL_BEFORE = {
  image: '',
  alt: 'Before project photo',
  label: 'Before',
  headline: 'Starting condition',
  detail: 'Site or scope before work began',
};

const NEUTRAL_AFTER = {
  image: '',
  alt: 'After project photo',
  label: 'After',
  headline: 'Finished result',
  detail: 'Delivered outcome after completion',
};

export const UNIVERSAL_BASELINE_BLOCK_DEFINITIONS: BuildBookBlockDefinition[] = [
  // —— Process timeline ——
  {
    id: 'universal-process-vertical',
    section: 'fold',
    label: 'Process timeline — vertical',
    description: 'Cross-template numbered steps — detailed how-it-works for any service business.',
    componentId: 'universal-process-vertical',
    layout: 'list',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['kicker', 'heading', 'steps'],
    defaultProps: {
      kicker: 'How it works',
      heading: 'From first contact to finished project',
      steps: structuredClone(NEUTRAL_PROCESS_STEPS),
    },
    seoRole: 'Captures process language for how-it-works and service education queries.',
    conversionRole: 'Reduces anxiety about what happens after the first inquiry.',
  },
  {
    id: 'universal-process-visual',
    section: 'fold',
    label: 'Process timeline — visual cards',
    description: 'Cross-template photo step cards — scannable grid for trades, consulting, and local services.',
    componentId: 'universal-process-visual',
    layout: 'cards',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 6 },
    editableFields: ['kicker', 'heading', 'steps'],
    defaultProps: {
      kicker: 'How it works',
      heading: 'What to expect when you hire us',
      steps: structuredClone(VISUAL_PROCESS_STEPS),
    },
    seoRole: 'Adds crawlable process copy with visual proof per project phase.',
    conversionRole: 'Helps visitors picture the engagement before they request a quote.',
  },
  // —— Stats band ——
  {
    id: 'universal-stats-compact',
    section: 'fold',
    label: 'Trust bar — compact',
    description: 'Cross-template four-metric strip — credibility above the fold on any template.',
    componentId: 'universal-stats-compact',
    layout: 'metrics',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 3 },
    editableFields: ['kicker', 'stats'],
    defaultProps: {
      kicker: 'Why homeowners choose us',
      stats: structuredClone(NEUTRAL_STATS),
    },
    seoRole: 'Adds crawlable proof metrics near the top of the page.',
    conversionRole: 'Reduces anxiety with longevity and licensing proof.',
  },
  {
    id: 'universal-stats-cards',
    section: 'fold',
    label: 'Trust bar — cards',
    description: 'Cross-template credential cards in a 2×2 grid — higher visual weight than a strip.',
    componentId: 'universal-stats-cards',
    layout: 'stats',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['kicker', 'heading', 'stats'],
    defaultProps: {
      kicker: 'Proof at a glance',
      heading: 'Numbers that back our work',
      stats: structuredClone(NEUTRAL_STATS),
    },
    seoRole: 'Supports authority with bold outcome metrics.',
    conversionRole: 'Builds confidence before visitors compare service options.',
  },
  // —— FAQ ——
  {
    id: 'universal-faq-accordion',
    section: 'areas',
    label: 'FAQ — accordion',
    description: 'Cross-template expandable FAQ — coverage, licensing, and quote questions.',
    componentId: 'universal-faq-accordion',
    layout: 'map',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 7 },
    editableFields: ['kicker', 'heading', 'subhead', 'items'],
    defaultProps: {
      kicker: 'FAQ',
      heading: 'Common questions',
      subhead: 'Quick answers about service area, quotes, licensing, and timelines.',
      items: structuredClone(NEUTRAL_FAQ),
    },
    seoRole: 'Captures long-tail FAQ language for local and service queries.',
    conversionRole: 'Answers logistics questions that otherwise delay contact.',
  },
  {
    id: 'universal-faq-two-col',
    section: 'areas',
    label: 'FAQ — two column',
    description: 'Cross-template Q&A grid — scannable without accordion interaction.',
    componentId: 'universal-faq-two-col',
    layout: 'map',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 7 },
    editableFields: ['kicker', 'heading', 'subhead', 'items'],
    defaultProps: {
      kicker: 'FAQ',
      heading: 'What people ask before they hire us',
      subhead: 'Coverage, quotes, credentials, and what to expect on site.',
      items: structuredClone(NEUTRAL_FAQ),
    },
    seoRole: 'Exposes FAQ entities for featured snippets and local search.',
    conversionRole: 'Removes friction for visitors comparing providers.',
  },
  // —— CTA banner ——
  {
    id: 'universal-cta-band',
    section: 'close',
    label: 'CTA banner — full band',
    description: 'Cross-template ink conversion band with headline, body, and primary action.',
    componentId: 'universal-cta-band',
    layout: 'close-form',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 4 },
    editableFields: ['heading', 'body', 'ctaLabel', 'ctaHref'],
    defaultProps: {
      heading: 'Ready to get started?',
      body: 'Tell us about your project and we will follow up with a clear next step — usually within one business day.',
      ctaLabel: 'Request a quote',
      ctaHref: '#inquiry',
    },
    seoRole: 'Connects page topic to a clear contact destination.',
    conversionRole: 'Captures the lead with a focused final action.',
  },
  {
    id: 'universal-cta-split',
    section: 'close',
    label: 'CTA banner — split',
    description: 'Cross-template split close — copy left, action right, optional photo.',
    componentId: 'universal-cta-split',
    layout: 'close-form',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['heading', 'body', 'ctaLabel', 'ctaHref', 'imageSrc', 'imageAlt'],
    defaultProps: {
      heading: 'Let’s talk about your project',
      body: 'Share scope, timing, and location. We will confirm fit and send a quote or schedule a walkthrough.',
      ctaLabel: 'Get in touch',
      ctaHref: '#inquiry',
      imageSrc: '',
      imageAlt: 'Team on site',
    },
    seoRole: 'Reinforces conversion intent with visual proof beside the CTA.',
    conversionRole: 'Gives hesitant visitors one last reason to reach out.',
  },
  // —— Testimonials ——
  {
    id: 'universal-reviews-grid',
    section: 'proof',
    label: 'Reviews — card grid',
    description: 'Cross-template three-card review grid — social proof for any service business.',
    componentId: 'universal-reviews-grid',
    layout: 'reviews',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 7 },
    editableFields: ['kicker', 'heading', 'testimonials'],
    defaultProps: {
      kicker: 'Client reviews',
      heading: 'What customers say about working with us',
      testimonials: structuredClone(NEUTRAL_TESTIMONIALS),
    },
    seoRole: 'Adds crawlable social proof language for trust queries.',
    conversionRole: 'Builds confidence before the final inquiry.',
  },
  {
    id: 'universal-reviews-quote',
    section: 'proof',
    label: 'Reviews — featured quote',
    description: 'Cross-template single large pull quote — hero testimonial for proof sections.',
    componentId: 'universal-reviews-quote',
    layout: 'reviews',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['kicker', 'heading', 'testimonials'],
    defaultProps: {
      kicker: 'Client review',
      heading: 'Trusted by homeowners and businesses',
      testimonials: structuredClone(NEUTRAL_TESTIMONIALS.slice(0, 1)),
    },
    seoRole: 'Featured testimonial copy for authority signals.',
    conversionRole: 'Anchors proof with one memorable client story.',
  },
  // —— Section intro ——
  {
    id: 'universal-intro-centered',
    section: 'fold',
    label: 'Section intro — centered',
    description: 'Cross-template centered eyebrow and lede — bridge between homepage sections.',
    componentId: 'universal-intro-centered',
    layout: 'band',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['kicker', 'heading', 'body'],
    defaultProps: {
      kicker: 'What we do',
      heading: 'Clear scope, honest timelines, work you can trust',
      body: 'We help clients move from first conversation to finished project with transparent quotes, licensed crews, and updates at every step.',
    },
    seoRole: 'Adds crawlable offer context between major page sections.',
    conversionRole: 'Frames the next section so visitors know why it matters.',
  },
  {
    id: 'universal-intro-split',
    section: 'fold',
    label: 'Section intro — split',
    description: 'Cross-template split intro with kicker beside body copy and accent rule.',
    componentId: 'universal-intro-split',
    layout: 'band',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['kicker', 'heading', 'body'],
    defaultProps: {
      kicker: 'Why it matters',
      heading: 'Built for real-world schedules and site constraints',
      body: 'Whether you need a fast repair or a multi-phase install, we scope the job clearly, confirm fit, and keep you informed from mobilization through wrap-up.',
    },
    seoRole: 'Supports topical relevance with bridge copy before service or proof blocks.',
    conversionRole: 'Sets expectations before visitors compare options.',
  },
  // —— Service grid ——
  {
    id: 'universal-services-grid',
    section: 'services',
    label: 'Services — photo grid',
    description: 'Cross-template 2×2 photo service cards — core offer block for any template.',
    componentId: 'universal-services-grid',
    layout: 'capabilities',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['kicker', 'heading', 'services'],
    defaultProps: {
      kicker: 'Services',
      heading: 'What we help clients with',
      services: structuredClone(NEUTRAL_SERVICES),
    },
    seoRole: 'Exposes service entities for local and topical search coverage.',
    conversionRole: 'Helps visitors self-select the offer that matches their need.',
  },
  {
    id: 'universal-services-list',
    section: 'services',
    label: 'Services — stacked list',
    description: 'Cross-template stacked service rows with chevron — scannable without a photo grid.',
    componentId: 'universal-services-list',
    layout: 'list',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['kicker', 'heading', 'services'],
    defaultProps: {
      kicker: 'Services',
      heading: 'Explore what we offer',
      services: structuredClone(NEUTRAL_SERVICES),
    },
    seoRole: 'Lists crawlable service titles and descriptions for search intent.',
    conversionRole: 'Routes visitors toward inquiry by service lane.',
  },
  // —— Content split ——
  {
    id: 'universal-split-image-right',
    section: 'proof',
    label: 'Content split — image right',
    description: 'Cross-template copy left, photo right — proof or story split for any vertical.',
    componentId: 'universal-split-image-right',
    layout: 'featured',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['kicker', 'heading', 'body', 'imageSrc', 'imageAlt'],
    defaultProps: {
      kicker: 'Why choose us',
      heading: 'Experience you can see on every job',
      body: 'We combine licensed crews, clear communication, and workmanship that holds up after the walkthrough — not just on day one.',
      imageSrc: '',
      imageAlt: 'Team at work on site',
      imagePosition: 'right',
    },
    seoRole: 'Adds proof copy paired with visual evidence.',
    conversionRole: 'Connects claims to concrete outcomes before contact.',
  },
  {
    id: 'universal-split-image-left',
    section: 'proof',
    label: 'Content split — image left',
    description: 'Cross-template photo left, copy right — alternate split for visual rhythm.',
    componentId: 'universal-split-image-left',
    layout: 'featured',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['kicker', 'heading', 'body', 'imageSrc', 'imageAlt'],
    defaultProps: {
      kicker: 'Our approach',
      heading: 'Planned work, documented results',
      body: 'From scope and permits to final inspection, we document milestones so you always know what was delivered and what comes next.',
      imageSrc: '',
      imageAlt: 'Finished project detail',
      imagePosition: 'left',
    },
    seoRole: 'Supports authority with narrative proof and imagery.',
    conversionRole: 'Reduces uncertainty for visitors comparing providers.',
  },
  // —— Work gallery ——
  {
    id: 'universal-gallery-grid',
    section: 'proof',
    label: 'Work gallery — uniform grid',
    description: 'Cross-template uniform three-column project gallery with captions.',
    componentId: 'universal-gallery-grid',
    layout: 'grid',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['kicker', 'heading', 'gallery'],
    defaultProps: {
      kicker: 'Recent work',
      heading: 'Projects we are proud to show',
      gallery: structuredClone(NEUTRAL_GALLERY),
    },
    seoRole: 'Portfolio imagery and captions for show-work queries.',
    conversionRole: 'Builds trust with visual proof before inquiry.',
  },
  {
    id: 'universal-gallery-masonry',
    section: 'proof',
    label: 'Work gallery — masonry',
    description: 'Cross-template masonry-style gallery — varied tile heights for visual interest.',
    componentId: 'universal-gallery-masonry',
    layout: 'grid',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['kicker', 'heading', 'gallery'],
    defaultProps: {
      kicker: 'Portfolio',
      heading: 'A closer look at recent jobs',
      gallery: structuredClone(NEUTRAL_GALLERY),
    },
    seoRole: 'Adds crawlable project captions beside portfolio imagery.',
    conversionRole: 'Helps visitors picture outcomes on their own property.',
  },
  // —— Case study ——
  {
    id: 'universal-case-featured',
    section: 'proof',
    label: 'Case study — featured',
    description: 'Cross-template split project story with photo — concrete proof for any vertical.',
    componentId: 'universal-case-featured',
    layout: 'featured',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['kicker', 'heading', 'body', 'imageSrc', 'imageAlt'],
    defaultProps: {
      kicker: 'Featured project',
      heading: 'Scope, execution, and a result worth showing',
      body: 'A recent engagement where we mobilized on schedule, documented each phase, and delivered a finished outcome the client could sign off with confidence.',
      imageSrc: '',
      imageAlt: 'Featured project photo',
    },
    seoRole: 'Case study narrative for E-E-A-T and outcome queries.',
    conversionRole: 'Turns capability into a concrete project story.',
  },
  {
    id: 'universal-case-metrics',
    section: 'proof',
    label: 'Case study — with metrics',
    description: 'Cross-template project panel with outcome metrics row — proof plus numbers.',
    componentId: 'universal-case-metrics',
    layout: 'featured',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['kicker', 'heading', 'caption', 'metrics', 'imageSrc', 'imageAlt'],
    defaultProps: {
      kicker: 'Project spotlight',
      heading: 'Delivered on time with measurable outcomes',
      caption: 'Client name · location · year',
      imageSrc: '',
      imageAlt: 'Project outcome photo',
      metrics: structuredClone(NEUTRAL_CASE_METRICS),
    },
    seoRole: 'Outcome metrics paired with project proof for authority.',
    conversionRole: 'Shows results beyond marketing claims.',
  },
  // —— Logo strip ——
  {
    id: 'universal-logos-row',
    section: 'proof',
    label: 'Logos — horizontal row',
    description: 'Cross-template partner logo row — B2B and manufacturer trust for any template.',
    componentId: 'universal-logos-row',
    layout: 'band',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 3.5 },
    editableFields: ['kicker', 'heading', 'logos'],
    defaultProps: {
      kicker: 'Trusted by',
      heading: 'Partners and clients we work with',
      logos: structuredClone(NEUTRAL_LOGOS),
    },
    seoRole: 'Named partner logos for authority and trust signals.',
    conversionRole: 'Signals credibility before visitors compare options.',
  },
  {
    id: 'universal-logos-grid',
    section: 'proof',
    label: 'Logos — two-row grid',
    description: 'Cross-template two-row partner grid — higher visual weight than a single strip.',
    componentId: 'universal-logos-grid',
    layout: 'band',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['kicker', 'heading', 'logos'],
    defaultProps: {
      kicker: 'Partners',
      heading: 'Organizations that trust our work',
      logos: structuredClone(NEUTRAL_LOGOS),
    },
    seoRole: 'Partner names and logos for institutional trust queries.',
    conversionRole: 'Builds confidence for B2B and referral visitors.',
  },
  // —— Before & after ——
  {
    id: 'universal-before-after',
    section: 'proof',
    label: 'Before & after — side by side',
    description: 'Cross-template side-by-side transformation proof — trades, landscaping, and remodel work.',
    componentId: 'universal-before-after',
    layout: 'split',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['kicker', 'heading', 'subhead', 'before', 'after'],
    defaultProps: {
      kicker: 'Results',
      heading: 'Before and after',
      subhead: 'Same property — clear improvement you can evaluate at a glance.',
      before: structuredClone(NEUTRAL_BEFORE),
      after: structuredClone(NEUTRAL_AFTER),
    },
    seoRole: 'Outcome proof imagery for conversion-oriented searches.',
    conversionRole: 'Visual proof before quote or contact requests.',
  },
  {
    id: 'universal-before-after-stack',
    section: 'proof',
    label: 'Before & after — stacked',
    description: 'Cross-template stacked before/after panels — mobile-first transformation proof.',
    componentId: 'universal-before-after-stack',
    layout: 'split',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['kicker', 'heading', 'subhead', 'before', 'after'],
    defaultProps: {
      kicker: 'Transformation',
      heading: 'See the difference',
      subhead: 'Starting condition and finished result from a recent client project.',
      before: structuredClone(NEUTRAL_BEFORE),
      after: structuredClone(NEUTRAL_AFTER),
    },
    seoRole: 'Before/after captions for show-work and outcome queries.',
    conversionRole: 'Helps hesitant visitors picture results on their site.',
  },
];

export function isUniversalBaselineBlockId(blockId: string | null | undefined): boolean {
  return Boolean(blockId?.startsWith('universal-'));
}
