import type { BuildBookBlockDefinition } from './build-book.types';

const WRI_PREVIEW_URL = 'https://45108834.cs-futureproof.pages.dev/lab/wri/option-2/2b/';
const WRI_GENERATED_BASE = 'https://45108834.cs-futureproof.pages.dev/wri/generated';

export const WRI_BASELINE_BLOCK_DEFINITIONS: BuildBookBlockDefinition[] = [
  {
    id: 'wri-baseline-hero-life-proof',
    section: 'hero',
    label: 'Life + proof hero',
    description: 'WRI Option 2B full-bleed life-theme hero with exact approved copy.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-hero',
    astroComponent: 'sites/futureproof/src/components/wri/heroes/WriHeroFullbleedRig.astro',
    layout: 'fullbleed',
    navThumbKind: 'wri-hero-fullbleed',
    navThumbAspect: { width: 16, height: 16 },
    editableFields: [
      'eyebrow',
      'heading',
      'subhead',
      'backgroundImageSrc',
      'backgroundImageAlt',
      'primaryCtaLabel',
      'primaryCtaHref',
      'secondaryCtaLabel',
      'secondaryCtaHref',
    ],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      optionId: 'option-2',
      option2VariantId: '2b',
      labUnit: 'components/wri/WriSite.astro',
      labBrand: 'wri',
      labLayout: 'wri-baseline-life-proof',
      labCatalog: 'heroes',
      eyebrow: 'Water bringing life to Hawaii',
      heading: 'Reliable groundwater from exploration through pump install.',
      subhead:
        'WRI develops the wells that feed agriculture, municipal supply, and private estates — with licensed crews mobilized statewide from Honolulu and Kawaihae.',
      backgroundImageSrc: `${WRI_GENERATED_BASE}/hero-life-coast.jpg`,
      backgroundImageAlt:
        'Aerial documentary photograph of Hawaii sea cliffs with natural green vegetation and Pacific surf',
      primaryCtaLabel: 'Request a quote',
      primaryCtaHref: '#quote',
      secondaryCtaLabel: 'Call (808) 531-8422',
      secondaryCtaHref: 'tel:+18085318422',
      phone: '(808) 531-8422',
    },
    seoRole: 'Sets the single H1, Hawaii groundwater service intent, and life-theme brand positioning.',
    conversionRole: 'Introduces quote and service paths while anchoring the approved WRI visual tone.',
  },
  {
    id: 'wri-baseline-contract-bar',
    section: 'fold',
    label: 'Contract credibility bar',
    description: 'Approved WRI contract proof bar rendered directly below the hero.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-contract-bar',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldContractBar.astro',
    layout: 'contract-bar',
    navThumbKind: 'wri-contract-bar',
    navThumbAspect: { width: 16, height: 3 },
    editableFields: ['stats', 'sectorsLine'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldContractBar.astro',
      labBrand: 'wri',
      labLayout: 'wri-baseline-contract-bar',
      labCatalog: 'fold',
      stats: [
        { value: '35+', label: 'Years in Hawaii' },
        { value: '$150M+', label: 'Contracts completed' },
        { value: '2,800 ft', label: 'Max well depth' },
        { value: 'Pacific Basin', label: 'coverage' },
      ],
      sectorsLine: 'Government · Commercial · Agricultural · Private · 35+ years · Pacific Basin',
    },
    seoRole: 'Adds crawlable trust proof and procurement credibility immediately after the hero.',
    conversionRole: 'Reduces buyer anxiety with contract, depth, and operating history proof.',
  },
  {
    id: 'wri-baseline-capabilities-grid',
    section: 'services',
    label: 'Capabilities grid',
    description: 'Approved WRI self-sort service cards for exploration, drilling, pump install, and monitoring.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-capabilities-grid',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldCapabilitiesGrid.astro',
    layout: 'capabilities',
    navThumbKind: 'wri-capabilities-grid',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['kicker', 'heading', 'lede', 'capabilities'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldCapabilitiesGrid.astro',
      labBrand: 'wri',
      labLayout: 'wri-fold-capabilities',
      labCatalog: 'fold',
      kicker: 'Capabilities',
      heading: 'Exploration through deep well pumping',
      lede: 'Groundwater resource development for government agencies, commercial developers, and private property owners across Hawaii.',
      capabilities: [
        {
          title: 'Groundwater exploration',
          body: 'Hydrogeologic assessment and site evaluation before mobilization — reducing dry-hole risk for developers and agencies.',
          image: `${WRI_GENERATED_BASE}/hero-life-valley.jpg`,
          href: '#services',
        },
        {
          title: 'Deep well drilling',
          body: 'Production wells to 2,800 ft with experienced drillers — the capability that built $150M+ in Hawaii contracts.',
          image: `${WRI_GENERATED_BASE}/hero-life-watershed.jpg`,
          href: '#services',
        },
        {
          title: 'Pump installation',
          body: 'Deep well pumping systems sized for municipal, agricultural, and commercial demand — install through commissioning.',
          image: `${WRI_GENERATED_BASE}/hero-life-taro.jpg`,
          href: '#services',
        },
        {
          title: 'Monitoring & testing',
          body: 'Yield testing, water quality sampling, and ongoing performance monitoring for permitted production wells.',
          image: `${WRI_GENERATED_BASE}/hero-life-fields.jpg`,
          href: 'tel:+18085318422',
        },
      ],
    },
    seoRole: 'Exposes core service entities for groundwater drilling and pump search intent.',
    conversionRole: 'Lets visitors self-select the service lane that matches their project.',
  },
  {
    id: 'wri-baseline-life-proof-split',
    section: 'proof',
    label: 'Life + proof split',
    description: 'Approved Option 2B SEO split intro block.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-seo-band',
    astroComponent: 'sites/futureproof/src/components/wri/WriSeoBand.astro',
    layout: 'split',
    navThumbKind: 'wri-copy-split',
    navThumbAspect: { width: 16, height: 6 },
    editableFields: ['kicker', 'heading', 'lede', 'bullets'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/WriSeoBand.astro',
      seoCopyBlockId: 'life-narrative-c',
      kicker: 'Life · reliability · depth',
      heading: 'Water resources engineering rooted in Hawaii place.',
      lede:
        'We drill where water matters most — coastal recharge zones, central valley agriculture, and upland estates that cannot depend on surface supply alone. Licensed crews, documented testing, and pump install close the loop.',
      bullets: [
        'Watershed-aware exploration methods',
        'Deep basalt drilling to 2,800 ft',
        'Pump install and yield verification',
        'Honolulu and Kawaihae mobilization',
      ],
    },
    seoRole: 'Adds keyword-rich process and place language without duplicating the hero H1.',
    conversionRole: 'Connects emotional life-theme messaging to concrete technical proof.',
  },
  {
    id: 'wri-baseline-project-lifecycle',
    section: 'areas',
    label: 'Project lifecycle',
    description: 'Approved WRI permit-to-production process section.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-project-lifecycle',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldProjectLifecycle.astro',
    layout: 'list',
    navThumbKind: 'wri-lifecycle',
    navThumbAspect: { width: 16, height: 4.5 },
    editableFields: ['title', 'steps'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldProjectLifecycle.astro',
      title: 'From exploration to production',
      steps: [
        {
          step: '01',
          title: 'Site assessment',
          body: 'Review geology, existing records, and permit requirements for your parcel and intended use.',
        },
        {
          step: '02',
          title: 'Permit & design',
          body: 'Coordinate county well permits, DOH requirements, and pump sizing with your project timeline.',
        },
        {
          step: '03',
          title: 'Drill & test',
          body: 'Mobilize certified drillers, complete the borehole, and run yield and water quality testing.',
        },
        {
          step: '04',
          title: 'Pump install',
          body: 'Install and commission deep well pumping systems matched to production and demand.',
        },
        {
          step: '05',
          title: 'Monitor',
          body: 'Document as-builts and optional monitoring for municipal, commercial, and agricultural clients.',
        },
      ],
    },
    seoRole: 'Captures project process language for procurement and owner education.',
    conversionRole: 'Shows a clear path from first conversation to commissioned well.',
  },
  {
    id: 'wri-baseline-featured-well',
    section: 'proof',
    label: 'Featured well',
    description: 'Approved WRI featured well proof section.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-featured-well',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldFeaturedWell.astro',
    layout: 'featured',
    navThumbKind: 'wri-featured-well',
    navThumbAspect: { width: 16, height: 10 },
    editableFields: ['kicker', 'heading', 'caption', 'metrics', 'imageSrc', 'imageAlt'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldFeaturedWell.astro',
      kicker: 'Featured well',
      heading: 'Deep production well — Central Oʻahu',
      caption: 'Municipal supply · basalt formation · 2024',
      metrics: [
        { label: 'Depth', value: '1,840 ft' },
        { label: 'Yield', value: '450 gpm' },
        { label: 'Formation', value: 'Basalt aquifer' },
        { label: 'Scope', value: 'Drill + pump + test' },
      ],
      imageSrc: `${WRI_GENERATED_BASE}/hero-life-valley.jpg`,
      imageAlt: 'Deep well drilling operation in Hawaii',
    },
    seoRole: 'Supplies E-E-A-T proof around well depth, yield, and field execution.',
    conversionRole: 'Turns abstract capability into a concrete project proof point.',
  },
  {
    id: 'wri-baseline-sidebar-facts',
    section: 'proof',
    label: 'Sidebar facts',
    description: 'Approved WRI mid-page narrative with sticky facts column.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-seo-band',
    astroComponent: 'sites/futureproof/src/components/wri/WriSeoBand.astro',
    layout: 'stats',
    navThumbKind: 'wri-sidebar-facts',
    navThumbAspect: { width: 16, height: 6 },
    editableFields: ['heading', 'lede', 'facts'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/WriSeoBand.astro',
      seoCopyBlockId: 'prose-sidebar',
      heading: 'Why Hawaii contractors choose WRI',
      lede:
        'Groundwater development is a long-term asset. WRI combines exploration discipline, deep drilling capability, and pump expertise so your well performs from commissioning through decades of production.',
      facts: [
        { label: 'Max depth', value: '2,800 ft' },
        { label: 'Contracts', value: '$150M+' },
        { label: 'Experience', value: 'Since 1989' },
        { label: 'Offices', value: 'Oahu · Big Island' },
      ],
    },
    seoRole: 'Reinforces expertise, experience, authority, and trust signals mid-page.',
    conversionRole: 'Keeps proof visible at the decision point before the close.',
  },
  {
    id: 'wri-baseline-regulatory-trust',
    section: 'proof',
    label: 'Regulatory trust',
    description: 'Approved WRI compliance and credential trust section.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-regulatory-trust',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldRegulatoryTrust.astro',
    layout: 'cards',
    navThumbKind: 'wri-regulatory-trust',
    navThumbAspect: { width: 16, height: 6 },
    editableFields: ['kicker', 'heading', 'credentials'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldRegulatoryTrust.astro',
      kicker: 'Compliance & credentials',
      heading: 'Licensed, permitted, and contract-proven',
      credentials: [
        {
          claim: 'State-licensed drillers',
          proof: 'Certified drilling crews with decades of Hawaii-specific formation experience.',
        },
        {
          claim: 'Permit coordination',
          proof: 'County well permits and DOH requirements managed through drilling and pump commissioning.',
        },
        {
          claim: 'Contract track record',
          proof: '35+ years and $150M+ in completed public and private contracts.',
        },
      ],
    },
    seoRole: 'Supports authority for regulated well drilling and pump installation queries.',
    conversionRole: 'Assures agency and private buyers that compliance is handled.',
  },
  {
    id: 'wri-baseline-island-coverage',
    section: 'areas',
    label: 'Island coverage',
    description: 'Approved WRI Hawaii island service coverage section.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-island-coverage',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldIslandCoverage.astro',
    layout: 'map',
    navThumbKind: 'wri-island-coverage',
    navThumbAspect: { width: 16, height: 10 },
    editableFields: ['kicker', 'heading', 'lede', 'mapCaption', 'offices', 'islands'],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldIslandCoverage.astro',
      kicker: 'Offices & coverage',
      heading: 'Honolulu headquarters · Kawaihae field office',
      lede: 'Mobilization across Oʻahu, Maui, Hawaiʻi Island, Kauaʻi, and the Pacific Basin for contract clients.',
      mapCaption: 'Alakea Street · Kawaihae Bay · Island-wide mobilization',
      offices: [
        {
          label: 'Honolulu',
          address: '1100 Alakea St., Suite 2900',
          city: 'Honolulu, HI 96813',
          phone: '(808) 531-8422',
        },
        {
          label: 'Big Island',
          address: '61-3295 Maluokalani St. Bay #1',
          city: 'Kawaihae, HI 96743',
          phone: '(808) 882-7207',
        },
      ],
      islands: ['Oahu', 'Maui', 'Hawaii Island', 'Kauai', 'Molokai', 'Lanai'],
    },
    seoRole: 'Adds local coverage language for Hawaii island and Pacific Basin searches.',
    conversionRole: 'Confirms mobilization reach for local and neighbor-island buyers.',
  },
  {
    id: 'wri-baseline-rig-gallery-cta',
    section: 'close',
    label: 'Rig gallery + quote CTA',
    description: 'Approved WRI field gallery and final quote CTA.',
    sourceTemplateId: 'wri-field-authority-v1',
    componentId: 'baseline-wri-rig-gallery-cta',
    astroComponent: 'sites/futureproof/src/components/wri/fold/WriFoldRigGalleryCta.astro',
    layout: 'close-form',
    navThumbKind: 'wri-gallery-cta',
    navThumbAspect: { width: 16, height: 12 },
    editableFields: [
      'heading',
      'body',
      'primaryCtaLabel',
      'primaryCtaHref',
      'secondaryCtaLabel',
      'secondaryCtaHref',
      'gallery',
    ],
    defaultProps: {
      baselineRenderer: 'wri-site',
      baselinePreviewUrl: WRI_PREVIEW_URL,
      labUnit: 'components/wri/fold/WriFoldRigGalleryCta.astro',
      heading: 'Ready to scope your well project?',
      body: 'Exploration, drilling, and pump installation for government, commercial, and private clients across Hawaii.',
      primaryCtaLabel: 'Submit project brief',
      primaryCtaHref: '#quote',
      secondaryCtaLabel: 'Call (808) 531-8422',
      secondaryCtaHref: 'tel:+18085318422',
      gallery: [
        { label: 'Watershed spring', image: `${WRI_GENERATED_BASE}/hero-life-watershed.jpg`, location: 'Oahu' },
        { label: 'Irrigation & fields', image: `${WRI_GENERATED_BASE}/hero-life-fields.jpg`, location: 'Hawaii Island' },
        { label: 'Coastal recharge', image: `${WRI_GENERATED_BASE}/hero-life-coast.jpg`, location: 'Maui' },
        { label: 'Banana spring', image: `${WRI_GENERATED_BASE}/hero-life-plants.jpg`, location: 'Kauai' },
        { label: 'Taro loi wetlands', image: `${WRI_GENERATED_BASE}/hero-life-taro.jpg`, location: 'Molokai' },
        { label: 'Misty valley river', image: `${WRI_GENERATED_BASE}/hero-life-valley.jpg`, location: 'Lanai' },
      ],
    },
    seoRole: 'Closes with service, location, and contact language tied to the page topic.',
    conversionRole: 'Moves qualified visitors into a quote conversation.',
  },
];
