import type { BuildBookBlockDefinition } from './build-book.types';

const WILCO_PREVIEW_URL = 'https://cs-consult-demo.pages.dev/';
const HERO_IMAGE =
  'https://images.unsplash.com/photo-1624469681156-4114efeb85a0?w=1920&q=80&auto=format&fit=crop';

const mkWilcoProps = (labUnit: string, extra: Record<string, unknown> = {}) => ({
  baselineRenderer: 'wilco-site',
  baselinePreviewUrl: WILCO_PREVIEW_URL,
  labUnit,
  labBrand: 'consult',
  labCatalog: 'fold',
  ...extra,
});

const coreServices = [
  {
    heading: 'Septic installations',
    body: 'Engineer-spec systems, leach fields, and ADEC-ready documentation.',
    imageSrc:
      'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=640&h=800&auto=format&fit=crop&q=80',
    imageAlt: 'Trench excavation for underground utility installation',
    href: '#inquiry',
  },
  {
    heading: 'Civil grading',
    body: 'Cut-and-fill, drainage, and compaction from civil plans.',
    imageSrc:
      'https://images.unsplash.com/photo-1703180505804-d7e5a84912cc?w=640&h=800&auto=format&fit=crop&q=80',
    imageAlt: 'Bulldozer grading a building site',
    href: '#inquiry',
  },
  {
    heading: 'Wastewater treatment',
    body: 'Package plants, lift stations, and effluent systems for rural sites.',
    imageSrc:
      'https://images.unsplash.com/photo-1775704012923-8a94fccad402?w=640&h=800&auto=format&fit=crop&q=80',
    imageAlt: 'Aerial view of a water treatment plant and reservoir',
    href: '#inquiry',
  },
  {
    heading: 'Construction pads',
    body: 'Engineered pads with subgrade prep and as-built surveys.',
    imageSrc:
      'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=640&h=800&auto=format&fit=crop&q=80',
    imageAlt: 'Residential construction site with framed building',
    href: '#inquiry',
  },
];

const partners = [
  {
    name: 'Alaska Native Tribal Health Consortium',
    href: 'https://anthc.org',
    logoSrc: 'https://anthc.org/wp-content/uploads/2024/02/anthc-logo.svg',
    logoAlt: 'Alaska Native Tribal Health Consortium logo',
  },
  {
    name: 'Seldovia Village Tribe',
    href: 'https://svt.org',
    logoSrc: 'https://svt.org/wp-content/uploads/2019/03/SVT-logo.png',
    logoAlt: 'Seldovia Village Tribe logo',
  },
  {
    name: 'Alaska Wildlife Conservation Center',
    href: 'https://alaskawildlife.org',
    logoSrc:
      'https://alaskawildlife.org/wp-content/uploads/2021/09/AWCC_Color2_Text_72ppi.png',
    logoAlt: 'Alaska Wildlife Conservation Center logo',
  },
];

const faqItems = [
  {
    question: 'What areas do you serve?',
    answer:
      "We work across Alaska's remote islands — Southeast archipelago, Kodiak, the Aleutians, and roadless coastal parcels. Share your island name or coordinates and we will confirm mobilization, barge landings, and season windows.",
  },
  {
    question: 'Do you handle remote or off-grid sites?',
    answer:
      "Yes. We plan for barge landings, tidal access, limited staging area, and short seasons common on Alaska's islands. Equipment is selected for shore-side footprints where full-size excavators cannot reach.",
  },
  {
    question: 'Do you work with civil engineers on permits?',
    answer:
      'Regularly. We implement grading, drainage, and septic layouts from Alaska civil engineers and document as-builts for municipal, ADEC, and COSA review.',
  },
  {
    question: 'Are you licensed and insured?',
    answer:
      'Wilco Consulting is fully licensed and carries liability insurance for excavation and site-work projects statewide.',
  },
];

export const WILCO_BASELINE_BLOCK_DEFINITIONS: BuildBookBlockDefinition[] = [
  {
    id: 'wilco-baseline-hero-split',
    section: 'hero',
    label: 'Split hero',
    description: 'Wilco split-layout hero with photo blade and dual CTAs.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-hero-split',
    astroComponent: '@client-sites/theme/components/landing/ConsultHeroSplit.astro',
    layout: 'split',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 10 },
    editableFields: ['heading', 'subhead', 'imageSrc', 'imageAlt', 'primaryCtaLabel', 'primaryCtaHref', 'secondaryCtaLabel', 'secondaryCtaHref'],
    defaultProps: mkWilcoProps('ConsultHeroSplit.astro', {
      labCatalog: 'heroes',
      labLayout: 'wilco-baseline-split',
      heading: 'Civil Infrastructure Consulting For Rural Alaska',
      subhead: 'From Engineering to Project Execution & Logistics We Get it done',
      imageSrc: HERO_IMAGE,
      imageAlt: 'Brown grass field near mountains under a blue sky',
      imagePosition: 'left',
      primaryCtaLabel: 'Call now',
      primaryCtaHref: 'tel:+19075550198',
      secondaryCtaLabel: 'Learn more',
      secondaryCtaHref: '#services',
    }),
    seoRole: 'Sets H1, Alaska civil consulting intent, and primary call path.',
    conversionRole: 'Introduces call and services paths with authority tone.',
  },
  {
    id: 'wilco-baseline-stats-band',
    section: 'fold',
    label: 'Stats band',
    description: 'Four-stat credibility strip below the hero.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-stats-band',
    astroComponent: '@client-sites/theme/components/landing/ConsultStatsBand.astro',
    layout: 'metrics',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 3 },
    editableFields: ['stats'],
    defaultProps: mkWilcoProps('ConsultStatsBand.astro', {
      labLayout: 'wilco-baseline-stats-band',
      stats: [
        { value: '15+', label: 'Years in rural Alaska' },
        { value: '200+', label: 'Projects completed' },
        { value: '24/7', label: 'Season-ready crews' },
        { value: '100%', label: 'Licensed & insured' },
      ],
    }),
    seoRole: 'Adds crawlable proof metrics near the top of the page.',
    conversionRole: 'Reduces anxiety with longevity and licensing proof.',
  },
  {
    id: 'wilco-baseline-trusted-by',
    section: 'fold',
    label: 'Trusted by',
    description: 'Partner logo strip for tribal and municipal clients.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-trusted-by',
    astroComponent: '@client-sites/theme/components/landing/ConsultTrustedBy.astro',
    layout: 'band',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 3 },
    editableFields: ['heading', 'partners'],
    defaultProps: mkWilcoProps('ConsultTrustedBy.astro', {
      labLayout: 'wilco-baseline-trusted-by',
      heading: 'Trusted by',
      partners,
    }),
    seoRole: 'Named client logos for authority signals.',
    conversionRole: 'Signals experience with institutional clients.',
  },
  {
    id: 'wilco-baseline-services-intro',
    section: 'services',
    label: 'Services intro',
    description: 'Split services overview with keyword chips.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-services-intro',
    astroComponent: '@client-sites/theme/components/landing/ConsultServicesIntro.astro',
    layout: 'list',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 6 },
    editableFields: ['eyebrow', 'heading', 'lead', 'keywords'],
    defaultProps: mkWilcoProps('ConsultServicesIntro.astro', {
      variant: 'split',
      eyebrow: 'What we do',
      heading: 'Civil infrastructure for rural Alaska',
      lead: 'Septic, grading, wastewater, and construction pads — scoped for remote parcels, barge windows, and short Alaska seasons.',
      keywords: [
        'Septic installation',
        'Civil grading',
        'Wastewater treatment',
        'Construction pads',
        'Southeast Alaska',
        'Kodiak & Aleutians',
        'Remote site work',
        'Licensed & insured',
      ],
    }),
    seoRole: 'Exposes service entities and geo keywords for Alaska search.',
    conversionRole: 'Helps visitors self-select service categories.',
  },
  {
    id: 'wilco-baseline-core-services',
    section: 'services',
    label: 'Core services grid',
    description: 'Four photo service cards with overlay copy.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-core-services',
    astroComponent: '@client-sites/theme/components/landing/ConsultCoreServices.astro',
    layout: 'capabilities',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 9 },
    editableFields: ['heading', 'services'],
    defaultProps: mkWilcoProps('ConsultCoreServices.astro', {
      variant: 'cards',
      heading: 'Core services',
      services: coreServices,
    }),
    seoRole: 'Core service entities for local and regional search.',
    conversionRole: 'Routes visitors to inquiry by service lane.',
  },
  {
    id: 'wilco-baseline-projects-intro',
    section: 'proof',
    label: 'Projects intro',
    description: 'Featured projects section heading and lede.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-projects-intro',
    astroComponent: 'consult-demo/projects-intro',
    layout: 'band',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 4 },
    editableFields: ['heading', 'body'],
    defaultProps: mkWilcoProps('projects-intro', {
      heading: 'Featured projects',
      body: 'Recent civil, septic, and wastewater work for tribal, municipal, and community clients statewide.',
    }),
    seoRole: 'Project proof section entry for E-E-A-T.',
    conversionRole: 'Frames case studies before project splits.',
  },
  {
    id: 'wilco-baseline-project-awcc',
    section: 'proof',
    label: 'Project · AWCC septic',
    description: 'Split project proof panel with image right.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-project-split',
    astroComponent: '@client-sites/theme/components/landing/ConsultServiceSplit.astro',
    layout: 'featured',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['eyebrow', 'heading', 'paragraphs', 'imageSrc', 'imageAlt', 'ctaLabel', 'ctaHref'],
    defaultProps: mkWilcoProps('ConsultServiceSplit.astro', {
      variant: 'panel',
      eyebrow: 'Project',
      heading: 'Alaska Wildlife Center septic installation',
      paragraphs: [
        'Engineer-spec septic system and leach field for the Alaska Wildlife Conservation Center — excavation, tank set, and tie-ins documented for ADEC and municipal inspection on a remote Turnagain Arm parcel.',
      ],
      imageSrc:
        'https://images.unsplash.com/photo-1768406938495-b72600c52cbe?w=960&h=960&auto=format&fit=crop&q=80',
      imageAlt: 'Excavator working on a rural construction site',
      imagePosition: 'right',
      ctaLabel: 'Discuss your project',
      ctaHref: '#inquiry',
    }),
    seoRole: 'Case study proof for septic and remote site work.',
    conversionRole: 'Turns capability into a concrete project story.',
  },
  {
    id: 'wilco-baseline-project-seldovia',
    section: 'proof',
    label: 'Project · Seldovia clinic',
    description: 'Split project proof panel with image left.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-project-split',
    astroComponent: '@client-sites/theme/components/landing/ConsultServiceSplit.astro',
    layout: 'featured',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['eyebrow', 'heading', 'paragraphs', 'imageSrc', 'imageAlt', 'ctaLabel', 'ctaHref'],
    defaultProps: mkWilcoProps('ConsultServiceSplit.astro', {
      variant: 'panel',
      eyebrow: 'Project',
      heading: 'Seldovia Village Clinic Civil Construction',
      paragraphs: [
        'Civil sitework and building pad for the Seldovia Village Tribe clinic — grading, utility trenches, and access prep coordinated with the project engineer through COSA-ready as-builts.',
      ],
      imageSrc:
        'https://images.unsplash.com/photo-1764885449332-7eb941d53b7e?w=960&h=960&auto=format&fit=crop&q=80',
      imageAlt: 'Modern community hospital building with trees in the foreground',
      imagePosition: 'left',
      ctaLabel: 'Discuss your project',
      ctaHref: '#inquiry',
    }),
    seoRole: 'Case study proof for civil and clinic sitework.',
    conversionRole: 'Builds trust with tribal and municipal audiences.',
  },
  {
    id: 'wilco-baseline-project-dillingham',
    section: 'proof',
    label: 'Project · Dillingham wastewater',
    description: 'Split project proof panel with image right.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-project-split',
    astroComponent: '@client-sites/theme/components/landing/ConsultServiceSplit.astro',
    layout: 'featured',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 8 },
    editableFields: ['eyebrow', 'heading', 'paragraphs', 'imageSrc', 'imageAlt', 'ctaLabel', 'ctaHref'],
    defaultProps: mkWilcoProps('ConsultServiceSplit.astro', {
      variant: 'panel',
      eyebrow: 'Project',
      heading: 'Wastewater and septic in Dillingham',
      paragraphs: [
        'Package wastewater treatment and on-site septic for a Dillingham site — lift station prep, effluent routing, and seasonal mobilization sequenced with Bristol Bay permit windows.',
      ],
      imageSrc:
        'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=960&h=960&auto=format&fit=crop&q=80',
      imageAlt: 'Industrial pipes and equipment at a treatment facility',
      imagePosition: 'right',
      ctaLabel: 'Discuss your project',
      ctaHref: '#inquiry',
    }),
    seoRole: 'Case study proof for wastewater treatment work.',
    conversionRole: 'Supports inquiry from Bristol Bay and remote sites.',
  },
  {
    id: 'wilco-baseline-testimonials',
    section: 'proof',
    label: 'Client testimonial',
    description: 'Featured client quote with attribution.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-testimonials',
    astroComponent: '@client-sites/theme/components/landing/TestimonialGrid.astro',
    layout: 'reviews',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 5 },
    editableFields: ['heading', 'testimonials'],
    defaultProps: mkWilcoProps('TestimonialGrid.astro', {
      heading: 'Client perspective',
      testimonials: [
        {
          quote:
            'Wilco cleared our island building pad and ran shore-side access — coordinated barge windows and finished before the weather closed in.',
          name: 'Sarah K.',
          role: 'Owner, remote island lodge — Southeast Alaska',
        },
      ],
    }),
    seoRole: 'Social proof language for trust queries.',
    conversionRole: 'Builds confidence before FAQ and CTA.',
  },
  {
    id: 'wilco-baseline-faq',
    section: 'close',
    label: 'FAQ accordion',
    description: 'Static FAQ list for Alaska service questions.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-faq',
    astroComponent: 'FaqAccordion',
    layout: 'list',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 7 },
    editableFields: ['heading', 'items'],
    defaultProps: mkWilcoProps('FaqAccordion', {
      heading: 'Frequently asked questions',
      items: faqItems,
    }),
    seoRole: 'FAQ content for long-tail Alaska contractor queries.',
    conversionRole: 'Answers objections before the call CTA.',
  },
  {
    id: 'wilco-baseline-call-cta',
    section: 'close',
    label: 'Call CTA band',
    description: 'Phone close band at the bottom of the page.',
    sourceTemplateId: 'wilco-consulting-v1',
    componentId: 'baseline-wilco-call-cta',
    astroComponent: 'consult-call-cta',
    layout: 'close-form',
    navThumbKind: 'generic',
    navThumbAspect: { width: 16, height: 3 },
    editableFields: ['phone', 'phoneHref', 'ctaLabel'],
    defaultProps: mkWilcoProps('consult-call-cta', {
      ctaLabel: 'Call now',
      phone: '(907) 555-0198',
      phoneHref: 'tel:+19075550198',
    }),
    seoRole: 'Closes page with contact intent.',
    conversionRole: 'Drives phone inquiries.',
  },
];
