import type { BuildBookTemplateDefinition } from './build-book.types';

export const BUILD_BOOK_TEMPLATE_DEFINITIONS: BuildBookTemplateDefinition[] = [
  {
    id: 'sparky-electric-trades-v1',
    label: 'Sparky Electric',
    category: 'Construction & trades',
    serviceOffered: 'Electrical Services',
    bestFor: 'Local contractors, electricians, HVAC, plumbing, and emergency service companies.',
    stack: 'Dispatch hero, trust stats, service cards, reviews, areas, quote CTA',
    theme: 'Trades conversion',
    accent: '#f59e0b',
    seoPurpose: 'Service + location visibility with crawlable services, proof, reviews, and FAQ targets.',
    conversionGoal: 'Drive calls, quote requests, and emergency dispatch paths.',
    visualTone: 'High-contrast, direct, urgent, local proof-heavy.',
    previewUrl: 'https://sparky3.pages.dev/',
    previewDescription: 'Local service template for emergency calls, quote requests, reviews, and service-area SEO.',
    previewKicker: 'Licensed electrical service',
    previewHeadline: 'Fast electrical help when the job cannot wait.',
    previewSubhead: 'Emergency repair, panel upgrades, generators, and code-safe installs for local homeowners.',
    previewStats: ['24/7 dispatch', '4.9 rating', 'Licensed crew'],
    previewSections: ['Emergency repairs', 'Panel upgrades', 'Generator installs', 'Service areas', 'Review proof', 'Quote CTA'],
    recommendedHeroId: 'sp-dispatch',
    recommendedFoldId: 'sp-fold-trust-stats',
    recommendedServicesId: 'svc-grid',
    defaultHomepageBlocks: [
      { section: 'hero', blockId: 'sp-dispatch' },
      { section: 'fold', blockId: 'sp-fold-trust-stats' },
      { section: 'services', blockId: 'svc-grid' },
      { section: 'proof', blockId: 'proof-reviews' },
      { section: 'areas', blockId: 'areas-faq' },
      { section: 'close', blockId: 'close-form' },
    ],
  },
  {
    id: 'wri-field-authority-v1',
    label: 'WRI Field Authority',
    category: 'Engineering & field services',
    serviceOffered: 'Field Services',
    bestFor: 'Technical, municipal, environmental, infrastructure, and field authority businesses.',
    stack: 'Metrics hero, contract credibility, capabilities, featured project, process, quote CTA',
    theme: 'Field authority',
    accent: '#0ea5e9',
    seoPurpose: 'Authority search visibility for technical services, sectors, credentials, and project evidence.',
    conversionGoal: 'Convert qualified project inquiries and procurement conversations.',
    visualTone: 'Serious, technical, credible, evidence-led.',
    previewUrl: 'https://45108834.cs-futureproof.pages.dev/lab/wri/option-2/2b/',
    previewDescription: 'Authority template for technical services, capabilities, credentials, and project proof.',
    previewKicker: 'Field authority',
    previewHeadline: 'Technical teams for complex field and infrastructure work.',
    previewSubhead: 'A procurement-ready homepage built around sectors, credentials, outcomes, and project evidence.',
    previewStats: ['40+ field programs', 'Municipal ready', 'Evidence-led'],
    previewSections: ['Contract credibility', 'Capabilities', 'Featured project', 'Sector proof', 'Process', 'Inquiry CTA'],
    recommendedHeroId: 'wri-metrics',
    recommendedFoldId: 'wri-fold-contract',
    recommendedServicesId: 'svc-cards',
    defaultHomepageBlocks: [
      { section: 'hero', blockId: 'wri-metrics' },
      { section: 'fold', blockId: 'wri-fold-contract' },
      { section: 'services', blockId: 'svc-cards' },
      { section: 'proof', blockId: 'proof-metrics' },
      { section: 'areas', blockId: 'areas-steps' },
      { section: 'close', blockId: 'close-banner' },
    ],
  },
  {
    id: 'wilco-consulting-v1',
    label: 'Wilco Consulting',
    category: 'Professional services',
    serviceOffered: 'Consulting Services',
    bestFor: 'Consultants, B2B advisory firms, agencies, and expert-led service businesses.',
    stack: 'Split hero, value services, proof, process, consultation CTA',
    theme: 'Restrained authority',
    accent: '#52525b',
    seoPurpose: 'Expertise-led visibility for service categories, thought leadership, and consultation intent.',
    conversionGoal: 'Book consultations and qualify B2B leads.',
    visualTone: 'Quiet confidence, editorial, clean, senior expert feel.',
    previewUrl: 'https://cs-consult-demo.pages.dev/',
    previewDescription: 'Professional services template for expertise, lead qualification, and consultation booking.',
    previewKicker: 'Advisory services',
    previewHeadline: 'Clear consulting direction for teams making high-stakes decisions.',
    previewSubhead: 'An editorial service site for positioning expertise, qualifying leads, and building trust before a call.',
    previewStats: ['Senior-led', 'B2B focus', 'Strategy first'],
    previewSections: ['Value proposition', 'Service lanes', 'Case proof', 'Advisory process', 'Insights', 'Consult CTA'],
    recommendedHeroId: 'co-split',
    recommendedFoldId: 'wri-fold-capabilities',
    recommendedServicesId: 'svc-list',
    defaultHomepageBlocks: [
      { section: 'hero', blockId: 'co-split' },
      { section: 'fold', blockId: 'wri-fold-capabilities' },
      { section: 'services', blockId: 'svc-list' },
      { section: 'proof', blockId: 'proof-quote' },
      { section: 'areas', blockId: 'areas-steps' },
      { section: 'close', blockId: 'close-banner' },
    ],
  },
  {
    id: 'veil-live-painter-v1',
    label: 'Live Wedding Painter',
    category: 'Wedding & events',
    serviceOffered: 'Live Event Painting',
    bestFor: 'Live wedding painters, event artists, and fine-art wedding creatives.',
    stack: 'Easel witness hero, process, portfolio, packages, reviews, availability, inquire',
    theme: 'Fine-art wedding',
    accent: '#c9a962',
    seoPurpose: 'Live wedding painter visibility with portfolio, process, packages, and date inquiry.',
    conversionGoal: 'Drive qualified date-check inquiries from engaged couples.',
    visualTone: 'Editorial, romantic, heirloom-focused, champagne and ivory palette.',
    previewUrl: 'https://cs-futureproof.pages.dev/lab/veil/easel-witness',
    previewDescription: 'Live wedding painter template with fine-art heroes, process proof, and date inquiry.',
    previewKicker: 'Live wedding painting',
    previewHeadline: 'Your wedding day, painted live.',
    previewSubhead: 'Ceremony through reception — one original canvas couples take home as a heirloom.',
    previewStats: ['12 hero layouts', 'Process proof', 'Date inquiry'],
    previewSections: ['Live process', 'Portfolio', 'Packages', 'Reviews', 'Availability', 'FAQ', 'Inquire'],
    recommendedHeroId: 'veil-easel-witness',
    recommendedFoldId: 'veil-baseline-fold-process',
    recommendedServicesId: 'svc-grid',
    defaultHomepageBlocks: [
      { section: 'hero', blockId: 'veil-easel-witness' },
      { section: 'fold', blockId: 'veil-baseline-fold-process' },
      { section: 'services', blockId: 'svc-grid' },
      { section: 'proof', blockId: 'proof-reviews' },
      { section: 'areas', blockId: 'areas-faq' },
      { section: 'close', blockId: 'veil-baseline-fold-inquire' },
    ],
  },
];

export function findBuildBookTemplate(templateId: string | null | undefined): BuildBookTemplateDefinition | undefined {
  if (!templateId) return undefined;
  return BUILD_BOOK_TEMPLATE_DEFINITIONS.find((template) => template.id === templateId);
}
