/** Dev Docs content — mirrors repo docs/ for in-app Stinger onboarding. */

export type DevDocCategory = 'start' | 'setup' | 'build' | 'ui' | 'ship';

export interface DevDocCategoryMeta {
  id: DevDocCategory;
  label: string;
  icon: string;
}

export const DEV_DOC_CATEGORIES: DevDocCategoryMeta[] = [
  { id: 'start', label: 'Start here', icon: 'pi pi-flag' },
  { id: 'setup', label: 'Setup', icon: 'pi pi-wrench' },
  { id: 'build', label: 'Build', icon: 'pi pi-code' },
  { id: 'ui', label: 'UI & contracts', icon: 'pi pi-palette' },
  { id: 'ship', label: 'Ship', icon: 'pi pi-send' },
];

export interface DevDocStep {
  title: string;
  body: string;
}

export interface DevDocLink {
  label: string;
  routerLink?: string;
  href?: string;
}

export interface DevDocEntry {
  id: string;
  title: string;
  category: DevDocCategory;
  description: string;
  paragraphs?: string[];
  steps?: DevDocStep[];
  code?: string;
  links?: DevDocLink[];
  keywords?: string[];
}

export const STINGER_CHECKLIST = [
  'Clone Sting and install dependencies',
  'Configure environment + Firebase project',
  'Add bagend CORS for your hosting URL',
  'Create your first feature route + nav item',
  'Browse UI Playground for PrimeNG patterns',
  'Lint, build prod, deploy',
] as const;

export const DEV_DOCS_CATALOG: DevDocEntry[] = [
  {
    id: 'welcome',
    title: 'Welcome, Stinger',
    category: 'start',
    description: 'What Sting is and how this guide fits your MVP workflow.',
    paragraphs: [
      'Sting is FieldWave’s rapid MVP launch pad — Angular 21, PrimeNG, alpha-layout shell, and @hive/contracts for typed APIs against bagend.',
      'Use this page as your starting line: work top-to-bottom, then jump to UI Playground when you need components.',
      'Repo markdown in docs/ stays the source of truth; this view is the dev-friendly scroll version.',
    ],
    links: [
      { label: 'UI Playground', routerLink: '/dev/ui' },
      { label: 'hive-contracts', href: 'https://github.com/farseer89/hive-contracts' },
    ],
    keywords: ['stinger', 'onboarding', 'intro'],
  },
  {
    id: 'local-dev',
    title: 'Local dev',
    category: 'start',
    description: 'Run the shell locally and use dev-only routes.',
    code: 'npm start\n# http://localhost:4200\n# Dev Docs + UI Playground in sidebar (enableDevRoutes)',
    paragraphs: [
      'Local builds set enableDevRoutes: true — you can browse the shell without remote bagend login.',
      'Production (stingbase) hides dev routes; auth and remote API apply there.',
    ],
    keywords: ['npm', 'localhost', 'enableDevRoutes'],
  },
  {
    id: 'launch-mvp',
    title: 'Launch a new MVP',
    category: 'start',
    description: 'End-to-end checklist from clone to first deploy.',
    steps: [
      { title: 'Clone', body: 'git clone https://github.com/farseer89/sting.git my-mvp && cd my-mvp' },
      { title: 'Install', body: 'npm install' },
      {
        title: 'Environment',
        body: 'cp src/environments/environment.template.ts src/environments/environment.prod.ts then STING_APP_NAME="My MVP" npm run configure-env',
      },
      { title: 'Firebase', body: 'npm run setup:firebase -- my-mvp-id then npm run deploy:firebase' },
      { title: 'bagend CORS', body: 'Add https://my-mvp-id.web.app to bagend allowlist' },
      { title: 'Hive', body: 'Keep @hive/contracts in sync (file:../hive-contracts or published package)' },
      {
        title: 'Feature',
        body: 'ng g component features/my-idea --standalone — register in app.routes.ts and navigation.service.ts',
      },
      { title: 'UI', body: 'Copy features/_templates/dashboard-kpi or browse /dev/ui' },
      { title: 'Lint', body: 'npm run lint before deploy' },
    ],
    keywords: ['launch', 'clone', 'deploy', 'checklist'],
  },
  {
    id: 'environment',
    title: 'Environment files',
    category: 'setup',
    description: 'environment.ts vs environment.prod.ts and configure-env.',
    paragraphs: [
      'environment.ts — local dev (enableDevRoutes: true, API URLs).',
      'environment.prod.ts — generated by scripts/replace-env.js at build time.',
      'Use @env/* path alias to import environments in app code.',
    ],
    code: 'cp src/environments/environment.template.ts src/environments/environment.prod.ts\nSTING_APP_NAME="My MVP" npm run configure-env',
    keywords: ['environment', 'configure-env'],
  },
  {
    id: 'firebase',
    title: 'Firebase hosting',
    category: 'setup',
    description: 'Setup script and deploy pipeline.',
    code: 'npm run setup:firebase -- my-mvp-id\nnpm run deploy:firebase',
    paragraphs: [
      'setup:firebase wires project id and hosting target.',
      'deploy:firebase runs build:prod then firebase deploy --only hosting.',
    ],
    keywords: ['firebase', 'hosting'],
  },
  {
    id: 'bagend-cors',
    title: 'bagend CORS',
    category: 'setup',
    description: 'Why localhost cannot call production bagend directly.',
    paragraphs: [
      'Remote droppin.shop CORS does not include localhost — local login to prod bagend will fail.',
      'Add your deployed https://<project>.web.app origin to bagend allowlist for production auth.',
      'For local API work, run bagend locally or use a dev proxy (not checked into Sting by default).',
    ],
    keywords: ['cors', 'bagend', 'auth'],
  },
  {
    id: 'architecture',
    title: 'Architecture & Sheriff',
    category: 'build',
    description: 'Layer boundaries enforced by npm run lint.',
    paragraphs: [
      'core/ — auth, config, guards (type:util)',
      'layout/ — alpha shell (type:shell)',
      'features/* — lazy routes (type:feature) — must not import other features',
      'shared/ui/ — presentational components (type:ui)',
    ],
    code: 'npm run lint             # ESLint + Sheriff dep rules\nnpm run architect:graph    # dependency graph\n# sheriff.config.ts',
    keywords: ['sheriff', 'layers', 'architecture'],
  },
  {
    id: 'add-feature',
    title: 'Adding a feature',
    category: 'build',
    description: 'Generate, route, and nav-register a new feature.',
    steps: [
      { title: 'Generate', body: 'ng generate component features/my-feature --standalone' },
      { title: 'PrimeNG', body: 'Add imports: [Card, Button, ...] on the component' },
      { title: 'Route', body: 'Lazy child under shell in app.routes.ts' },
      { title: 'Nav', body: 'Entry in navigation.service.ts' },
      { title: 'Verify', body: 'npm run build:prod before deploy' },
    ],
    code: `{
  path: 'my-feature',
  loadComponent: () =>
    import('./features/my-feature/my-feature.component').then((m) => m.MyFeatureComponent),
},`,
    keywords: ['feature', 'route', 'ng generate'],
  },
  {
    id: 'hive-contracts',
    title: 'Hive contracts',
    category: 'ui',
    description: 'Shared types between Sting, bagend, and other frontends.',
    steps: [
      { title: 'Define', body: 'Add types in @hive/contracts (UserPublic, SignInResponse, …)' },
      { title: 'Map', body: 'bagend: allowlist mappers (toUserPublic) — never spread toJSON()' },
      { title: 'UI', body: 'shared/ui components with input() typed from contracts' },
      { title: 'Feature', body: 'Services fetch typed data; smart components compose shared/ui' },
    ],
    links: [
      { label: 'hive-contracts repo', href: 'https://github.com/farseer89/hive-contracts' },
      { label: 'UI Playground (Hive)', routerLink: '/dev/ui' },
    ],
    keywords: ['hive', 'UserPublic', 'contracts'],
  },
  {
    id: 'templates',
    title: 'Templates & home layout',
    category: 'ui',
    description: 'Starting points for dashboard UI.',
    paragraphs: [
      'features/home/ — alpha-home reference (current landing).',
      'features/_templates/dashboard-kpi/ — KPI grid template (excluded from prod build in tsconfig).',
      'docs/primeng/ — LLM-oriented PrimeNG reference for agents and devs.',
    ],
    links: [{ label: 'UI Playground', routerLink: '/dev/ui' }],
    keywords: ['template', 'dashboard', 'kpi'],
  },
  {
    id: 'ui-playground',
    title: 'UI Playground',
    category: 'ui',
    description: 'PrimeNG block gallery with live previews.',
    paragraphs: [
      'Browse ~90 components with search, category filters, and copy-paste snippets.',
      'Hive category shows contract-bound examples before you extract to shared/ui.',
      'Style patterns tab: equipment list, toolbar, dashboard card (fw-* classes).',
    ],
    links: [{ label: 'Open UI Playground', routerLink: '/dev/ui' }],
    keywords: ['primeng', 'playground', 'blocks', 'patterns'],
  },
  {
    id: 'ui-patterns',
    title: 'UI style patterns',
    category: 'ui',
    description: 'Global fw-* classes for equipment tables and dashboard chrome.',
    paragraphs: [
      'Ported from probe telematics-equipment excel grid and dashboard-style-guide.',
      'See docs/UI_PATTERNS.md — apply fw-pattern-equipment-list on your feature root.',
    ],
    links: [{ label: 'UI Playground', routerLink: '/dev/ui' }],
    keywords: ['equipment', 'table', 'excel', 'probe'],
  },
  {
    id: 'deploy',
    title: 'Deploy checklist',
    category: 'ship',
    description: 'Before you ship an MVP.',
    steps: [
      { title: 'Lint', body: 'npm run lint — fix Sheriff boundary violations' },
      { title: 'Prod build', body: 'npm run build:prod' },
      { title: 'Deploy', body: 'npm run deploy:firebase' },
      { title: 'CORS', body: 'Confirm bagend allowlist includes your hosting URL' },
      { title: 'Contracts', body: 'Deploy bagend if API mappers changed' },
    ],
    keywords: ['deploy', 'production', 'firebase'],
  },
];
